// Level 4 Vocabulary (Ages 11+) - 7th-12th Grade
// Includes all Level 3 words plus advanced vocabulary

import { LEVEL_3_VOCABULARY } from './level3Vocabulary';

export const LEVEL_4_VOCABULARY = new Set([
  // Include all Level 3 words
  ...LEVEL_3_VOCABULARY,
  
  // Advanced 7th-12th Grade Vocabulary
  'abbreviate', 'abolish', 'abrasive', 'abrupt', 'abundance', 'accessible', 'accompany', 'accumulate', 'acknowledge', 'acquisition',
  'adamant', 'adequate', 'adjacent', 'adversary', 'advocate', 'aesthetic', 'affiliate', 'aggravate', 'allegiance', 'alleviate',
  'ambiguous', 'amplify', 'analogous', 'analyze', 'anarchy', 'ancestry', 'anticipate', 'apparatus', 'arbitrary', 'architect',
  'arithmetic', 'articulate', 'ascertain', 'assimilate', 'astute', 'atheist', 'atrocity', 'attribute', 'audacious', 'augment',
  'authentic', 'autonomous', 'aversion', 'bachelor', 'banish', 'belligerent', 'benevolent', 'bias', 'bizarre', 'blasphemy',
  'blatant', 'blockade', 'boisterous', 'boycott', 'budget', 'bureaucracy', 'caliber', 'campaign', 'campus', 'cancel',
  'candid', 'capable', 'capacity', 'capitalist', 'cardiac', 'casual', 'catalyst', 'catastrophe', 'category', 'caution',
  'cease', 'census', 'ceremony', 'chaos', 'character', 'charisma', 'charity', 'chronic', 'circuit', 'circumference',
  'circumstance', 'cite', 'civilian', 'clarify', 'classify', 'client', 'climate', 'coalition', 'coerce', 'coincide',
  'collaborate', 'collapse', 'colleague', 'colloquial', 'column', 'combat', 'combine', 'comedy', 'commission', 'commit',
  'committee', 'commodity', 'communicate', 'community', 'comparable', 'compatible', 'compensate', 'competent', 'compile', 'complement',
  'complex', 'component', 'comprehend', 'comprise', 'compromise', 'conceal', 'conceive', 'concentrate', 'concept', 'conclude',
  'condemn', 'condense', 'conduct', 'confer', 'confess', 'confide', 'confident', 'confine', 'conflict', 'conform',
  'confront', 'congress', 'conjecture', 'connect', 'conquer', 'conscience', 'conscious', 'consecutive', 'consent', 'consequence',
  'conservative', 'consider', 'consist', 'console', 'consolidate', 'conspiracy', 'constant', 'constitute', 'construct', 'consult',
  'consume', 'contact', 'contain', 'contaminate', 'contemplate', 'contemporary', 'content', 'contest', 'context', 'continent',
  'continue', 'contract', 'contradict', 'contrary', 'contrast', 'contribute', 'controversy', 'convenient', 'convention', 'convert',
  'convey', 'convince', 'cooperate', 'coordinate', 'corrupt', 'council', 'counsel', 'countless', 'couple', 'courage',
  'courteous', 'coward', 'create', 'creative', 'credible', 'crisis', 'criterion', 'crucial', 'crude', 'cruel',
  'cruise', 'cuisine', 'cultivate', 'culture', 'currency', 'custody', 'cycle', 'cynic', 'data', 'debate',
  'decade', 'decent', 'decision', 'decline', 'decompose', 'decrease', 'dedicate', 'deduct', 'defeat', 'defect',
  'defend', 'deficit', 'define', 'definite', 'delay', 'deliberate', 'delicate', 'delight', 'deliver', 'democracy',
  'demonstrate', 'dense', 'deny', 'depart', 'depend', 'depict', 'depression', 'derive', 'descend', 'describe',
  'desert', 'design', 'despair', 'desperate', 'despite', 'destroy', 'detail', 'detect', 'determine', 'develop',
  'device', 'devote', 'diagnose', 'diagram', 'dialogue', 'diameter', 'dictator', 'differ', 'difficult', 'digest',
  'dignity', 'dilemma', 'dimension', 'diminish', 'dinosaur', 'diploma', 'direct', 'directory', 'disappear', 'disaster',
  'discipline', 'discourse', 'discover', 'discuss', 'disease', 'disgrace', 'dismiss', 'disorder', 'display', 'dispose',
  'dispute', 'dissolve', 'distance', 'distinct', 'distinguish', 'distribute', 'district', 'diverse', 'divide', 'document',
  'domain', 'domestic', 'dominate', 'donate', 'drama', 'drastic', 'duration', 'dynamic', 'eager', 'earnest',
  'economy', 'edition', 'educate', 'efficient', 'elaborate', 'elastic', 'elect', 'electric', 'element', 'eliminate',
  'eloquent', 'embassy', 'emerge', 'emotion', 'emphasis', 'empire', 'employ', 'enable', 'encounter', 'encourage',
  'endorse', 'energy', 'enforce', 'engage', 'engine', 'enhance', 'enormous', 'ensure', 'entertain', 'entire',
  'entity', 'environment', 'episode', 'equal', 'equip', 'equivalent', 'era', 'error', 'establish', 'estimate',
  'ethics', 'ethnic', 'evaluate', 'event', 'evidence', 'evident', 'evolve', 'exact', 'exaggerate', 'examine',
  'example', 'exceed', 'excel', 'except', 'exchange', 'exclude', 'execute', 'exempt', 'exercise', 'exhaust',
  'exhibit', 'exist', 'expand', 'expect', 'expel', 'expense', 'experience', 'experiment', 'expert', 'explain',
  'explicit', 'explore', 'export', 'expose', 'express', 'extend', 'extent', 'external', 'extract', 'extreme',
  'fabric', 'factor', 'faculty', 'familiar', 'fascinate', 'feasible', 'feature', 'federal', 'fertile', 'fiction',
  'finance', 'flexible', 'fluid', 'focus', 'forbid', 'forecast', 'foreign', 'format', 'formula', 'fortune',
  'foundation', 'fragment', 'framework', 'fraud', 'frequent', 'frontier', 'function', 'fundamental', 'furnish', 'galaxy',
  'gender', 'generate', 'generic', 'genuine', 'geography', 'gesture', 'global', 'glory', 'govern', 'graduate',
  'grant', 'graphic', 'grasp', 'gravity', 'guarantee', 'guard', 'guide', 'habitat', 'halt', 'handicap',
  'harbor', 'harmony', 'harvest', 'hazard', 'headquarters', 'heritage', 'hierarchy', 'highlight', 'hire', 'historian',
  'historic', 'horizontal', 'hostile', 'household', 'however', 'humble', 'hurricane', 'hypothesis', 'ideal', 'identical',
  'identify', 'ideology', 'ignorant', 'illegal', 'illusion', 'illustrate', 'image', 'immigrate', 'immune', 'impact',
  'implement', 'implicit', 'imply', 'import', 'impose', 'impress', 'improve', 'impulse', 'incident', 'incline',
  'include', 'income', 'increase', 'incredible', 'indeed', 'independent', 'index', 'indicate', 'individual', 'induce',
  'industry', 'inevitable', 'infer', 'inferior', 'infinite', 'inflate', 'influence', 'inform', 'inhabit', 'inherit',
  'initial', 'initiate', 'inject', 'injure', 'innocent', 'innovate', 'input', 'inquire', 'insert', 'insight',
  'inspect', 'inspire', 'install', 'instance', 'instant', 'instead', 'institute', 'instruct', 'instrument', 'insult',
  'integrate', 'intellect', 'intelligent', 'intend', 'intense', 'interact', 'interest', 'interfere', 'internal', 'interpret',
  'interrupt', 'interval', 'interview', 'intimate', 'introduce', 'invade', 'invest', 'investigate', 'invite', 'involve',
  'isolate', 'issue', 'item', 'journal', 'journey', 'judge', 'judgment', 'jungle', 'junior', 'justice',
  'justify', 'keen', 'kernel', 'key', 'kidnap', 'kitchen', 'labor', 'laboratory', 'landscape', 'language',
  'large', 'laser', 'launch', 'layer', 'lead', 'league', 'lean', 'lease', 'leather', 'lecture',
  'legal', 'legend', 'legislate', 'legitimate', 'leisure', 'length', 'level', 'liability', 'liberal', 'liberty',
  'license', 'limit', 'linear', 'liquid', 'literature', 'loan', 'lobby', 'local', 'locate', 'logic',
  'loyal', 'machine', 'magic', 'magnetic', 'maintain', 'major', 'manage', 'mandate', 'manifest', 'manipulate',
  'manufacture', 'margin', 'marine', 'market', 'marriage', 'massive', 'master', 'material', 'mathematics', 'matter',
  'mature', 'maximum', 'mayor', 'meadow', 'meaning', 'measure', 'mechanism', 'media', 'medical', 'medium',
  'member', 'memory', 'mental', 'mention', 'merchant', 'mercy', 'merge', 'merit', 'method', 'metric',
  'middle', 'military', 'million', 'mineral', 'minimum', 'minister', 'minor', 'minority', 'minute', 'miracle',
  'mirror', 'missile', 'mission', 'mistake', 'mixture', 'mobile', 'model', 'moderate', 'modern', 'modify',
  'module', 'moment', 'monitor', 'moral', 'mortgage', 'motion', 'motivate', 'motive', 'mountain', 'movement',
  'multiple', 'muscle', 'museum', 'music', 'mutual', 'mystery', 'myth', 'narrative', 'nation', 'native',
  'natural', 'nature', 'navigate', 'necessary', 'negative', 'neglect', 'negotiate', 'neighbor', 'network', 'neutral',
  'nevertheless', 'noble', 'normal', 'notice', 'notion', 'novel', 'nuclear', 'number', 'numerous', 'nurse',
  'object', 'objective', 'obligation', 'observe', 'obstacle', 'obtain', 'obvious', 'occasion', 'occupy', 'occur',
  'ocean', 'offense', 'offer', 'office', 'officer', 'official', 'operate', 'opinion', 'opponent', 'opportunity',
  'oppose', 'opposite', 'option', 'oral', 'orbit', 'order', 'ordinary', 'organ', 'organize', 'orient',
  'origin', 'original', 'outcome', 'output', 'outstanding', 'overall', 'overcome', 'overlook', 'overseas', 'overview',
  'pace', 'package', 'panel', 'paper', 'paragraph', 'parallel', 'parameter', 'parent', 'parliament', 'participate',
  'particle', 'particular', 'partner', 'passage', 'passion', 'passive', 'patent', 'patience', 'patient', 'pattern',
  'pause', 'peace', 'peak', 'peasant', 'penalty', 'pending', 'pension', 'people', 'perceive', 'percent',
  'perfect', 'perform', 'perhaps', 'period', 'permanent', 'permit', 'person', 'personal', 'perspective', 'persuade',
  'phase', 'phenomenon', 'philosophy', 'phrase', 'physical', 'picture', 'piece', 'pilot', 'pioneer', 'pipe',
  'pitch', 'place', 'plain', 'planet', 'plant', 'plastic', 'platform', 'play', 'pleasant', 'please',
  'pleasure', 'plot', 'plus', 'pocket', 'poem', 'poet', 'poetry', 'point', 'policy', 'political',
  'politician', 'politics', 'poll', 'pollution', 'popular', 'population', 'port', 'portion', 'portrait', 'portray',
  'position', 'positive', 'possess', 'possible', 'post', 'potential', 'pound', 'poverty', 'power', 'practical',
  'practice', 'praise', 'pray', 'precise', 'predict', 'prefer', 'pregnant', 'prejudice', 'premium', 'prepare',
  'present', 'preserve', 'president', 'press', 'pressure', 'pretend', 'prevent', 'previous', 'price', 'pride',
  'priest', 'primary', 'prime', 'principal', 'principle', 'print', 'prior', 'priority', 'prison', 'private',
  'probably', 'problem', 'procedure', 'proceed', 'process', 'produce', 'product', 'profession', 'professor', 'profile',
  'profit', 'program', 'project', 'promise', 'promote', 'prompt', 'proof', 'proper', 'property', 'proportion',
  'proposal', 'propose', 'prospect', 'protect', 'protest', 'proud', 'prove', 'provide', 'province', 'provision',
  'psychology', 'public', 'publish', 'pull', 'punish', 'purchase', 'pure', 'purpose', 'pursue', 'push',
  'qualify', 'quality', 'quantity', 'quarter', 'question', 'quick', 'quiet', 'quit', 'quote', 'race',
  'radical', 'radio', 'rail', 'rain', 'raise', 'range', 'rank', 'rapid', 'rare', 'rate',
  'rather', 'ratio', 'rational', 'raw', 'reach', 'react', 'read', 'ready', 'real', 'reality',
  'realize', 'reason', 'rebel', 'recall', 'receive', 'recent', 'recognize', 'recommend', 'record', 'recover',
  'recruit', 'reduce', 'refer', 'reflect', 'reform', 'refuse', 'regard', 'region', 'register', 'regular',
  'regulate', 'reject', 'relate', 'relation', 'relative', 'relax', 'release', 'relevant', 'reliable', 'relief',
  'religion', 'rely', 'remain', 'remark', 'remember', 'remind', 'remove', 'repair', 'repeat', 'replace',
  'reply', 'report', 'represent', 'republic', 'reputation', 'request', 'require', 'rescue', 'research', 'resemble',
  'reserve', 'resident', 'resist', 'resolve', 'resource', 'respect', 'respond', 'response', 'responsible', 'restore',
  'restrict', 'result', 'resume', 'retail', 'retire', 'retreat', 'return', 'reveal', 'revenue', 'reverse',
  'review', 'revolution', 'reward', 'rhythm', 'rich', 'ridiculous', 'rifle', 'right', 'rigid', 'ring',
  'rise', 'risk', 'ritual', 'rival', 'river', 'road', 'robot', 'rock', 'role', 'roll',
  'romantic', 'roof', 'room', 'root', 'rope', 'rotate', 'rough', 'round', 'route', 'routine',
  'royal', 'rub', 'rule', 'run', 'rural', 'rush', 'sacred', 'sacrifice', 'safe', 'sail',
  'saint', 'sake', 'salary', 'sale', 'salt', 'sample', 'satellite', 'satisfy', 'sauce', 'save',
  'scale', 'scan', 'scandal', 'scene', 'schedule', 'scheme', 'scholar', 'scholarship', 'school', 'science',
  'scope', 'score', 'screen', 'script', 'sculpture', 'sea', 'search', 'season', 'seat', 'second',
  'secret', 'secretary', 'section', 'sector', 'secure', 'security', 'seed', 'seek', 'seem', 'select',
  'self', 'sell', 'senate', 'senator', 'send', 'senior', 'sense', 'sensitive', 'sentence', 'separate',
  'sequence', 'series', 'serious', 'serve', 'service', 'session', 'settle', 'setup', 'seven', 'several',
  'severe', 'sex', 'shade', 'shadow', 'shake', 'shall', 'shame', 'shape', 'share', 'sharp',
  'shelter', 'shift', 'shine', 'ship', 'shirt', 'shock', 'shoe', 'shoot', 'shop', 'shore',
  'short', 'shot', 'shoulder', 'shout', 'show', 'shut', 'sick', 'side', 'sight', 'sign',
  'signal', 'silence', 'silly', 'silver', 'similar', 'simple', 'since', 'sing', 'single', 'sink',
  'sister', 'site', 'situation', 'size', 'skill', 'skin', 'sky', 'slave', 'sleep', 'slide',
  'slight', 'slip', 'slow', 'small', 'smart', 'smile', 'smoke', 'smooth', 'snap', 'snow',
  'so', 'soap', 'social', 'society', 'sociology', 'sock', 'soft', 'software', 'soil', 'solar',
  'soldier', 'solid', 'solution', 'solve', 'some', 'somebody', 'somehow', 'someone', 'something', 'sometimes',
  'somewhat', 'somewhere', 'son', 'song', 'soon', 'sophisticated', 'sort', 'soul', 'sound', 'soup',
  'source', 'south', 'space', 'spare', 'speak', 'special', 'species', 'specific', 'speech', 'speed',
  'spell', 'spend', 'sphere', 'spin', 'spirit', 'spite', 'split', 'spokesman', 'sport', 'spot',
  'spread', 'spring', 'square', 'stable', 'staff', 'stage', 'stain', 'stair', 'stake', 'stand',
  'standard', 'star', 'stare', 'start', 'state', 'station', 'status', 'stay', 'steady', 'steal',
  'steel', 'step', 'stick', 'still', 'stimulate', 'stock', 'stomach', 'stone', 'stop', 'storage',
  'store', 'storm', 'story', 'straight', 'strain', 'strange', 'stranger', 'strategy', 'stream', 'street',
  'strength', 'stress', 'stretch', 'strike', 'string', 'strip', 'stroke', 'strong', 'structure', 'struggle',
  'student', 'studio', 'study', 'stuff', 'stupid', 'style', 'subject', 'submit', 'subsequent', 'substance',
  'substantial', 'substitute', 'subtle', 'suburb', 'succeed', 'success', 'such', 'sudden', 'suffer', 'sufficient',
  'sugar', 'suggest', 'suit', 'summer', 'summit', 'sun', 'super', 'superior', 'supply', 'support',
  'suppose', 'suppress', 'sure', 'surface', 'surgery', 'surprise', 'surround', 'survey', 'survive', 'suspect',
  'sustain', 'swear', 'sweep', 'sweet', 'swim', 'swing', 'switch', 'symbol', 'sympathy', 'symptom',
  'system', 'table', 'tackle', 'tail', 'take', 'tale', 'talent', 'talk', 'tall', 'tank',
  'tape', 'target', 'task', 'taste', 'tax', 'tea', 'teach', 'teacher', 'team', 'tear',
  'technical', 'technique', 'technology', 'telephone', 'telescope', 'television', 'tell', 'temperature', 'temple', 'temporary',
  'ten', 'tend', 'tennis', 'tension', 'tent', 'term', 'terminal', 'terrible', 'territory', 'terror',
  'test', 'text', 'than', 'thank', 'that', 'theater', 'their', 'them', 'theme', 'themselves',
  'then', 'theory', 'therapy', 'there', 'therefore', 'these', 'they', 'thick', 'thin', 'thing',
  'think', 'third', 'this', 'thorough', 'those', 'though', 'thought', 'thousand', 'threat', 'threaten',
  'three', 'through', 'throughout', 'throw', 'thumb', 'thus', 'ticket', 'tie', 'tight', 'time',
  'tiny', 'tip', 'tire', 'tissue', 'title', 'tobacco', 'today', 'toe', 'together', 'toilet',
  'tomato', 'tone', 'tongue', 'tonight', 'tool', 'tooth', 'top', 'topic', 'total', 'touch',
  'tough', 'tour', 'tourist', 'tournament', 'toward', 'tower', 'town', 'toy', 'track', 'trade',
  'tradition', 'traffic', 'train', 'training', 'transfer', 'transform', 'transition', 'translate', 'transport', 'trap',
  'travel', 'treat', 'treatment', 'tree', 'tremendous', 'trend', 'trial', 'tribe', 'trick', 'trip',
  'troop', 'trouble', 'truck', 'true', 'trust', 'truth', 'try', 'tube', 'tune', 'tunnel',
  'turn', 'twelve', 'twenty', 'twice', 'twin', 'two', 'type', 'typical', 'ugly', 'ultimate',
  'unable', 'uncle', 'under', 'undergo', 'understand', 'undertake', 'unemployment', 'unexpected', 'unfortunately', 'uniform',
  'union', 'unique', 'unit', 'unite', 'unity', 'universe', 'university', 'unknown', 'unless', 'unlike',
  'unlikely', 'until', 'unusual', 'up', 'upon', 'upper', 'urban', 'urge', 'urgent', 'use',
  'used', 'useful', 'user', 'usual', 'utility', 'vacation', 'valley', 'valuable', 'value', 'variable',
  'variation', 'variety', 'various', 'vast', 'vegetable', 'vehicle', 'venture', 'version', 'versus', 'vertical',
  'very', 'vessel', 'veteran', 'via', 'victim', 'victory', 'video', 'view', 'village', 'violate',
  'violence', 'violent', 'virtual', 'virtue', 'virus', 'visible', 'vision', 'visit', 'visual', 'vital',
  'voice', 'volume', 'volunteer', 'vote', 'wage', 'wait', 'wake', 'walk', 'wall', 'want',
  'war', 'warm', 'warn', 'warning', 'wash', 'waste', 'watch', 'water', 'wave', 'way',
  'weak', 'wealth', 'weapon', 'wear', 'weather', 'web', 'wedding', 'week', 'weekend', 'weekly',
  'weight', 'welcome', 'welfare', 'well', 'west', 'western', 'what', 'whatever', 'wheel', 'when',
  'whenever', 'where', 'whereas', 'wherever', 'whether', 'which', 'while', 'whisper', 'white', 'who',
  'whole', 'whom', 'whose', 'why', 'wide', 'wife', 'wild', 'will', 'willing', 'win',
  'wind', 'window', 'wine', 'wing', 'winner', 'winter', 'wire', 'wise', 'wish', 'with',
  'withdraw', 'within', 'without', 'witness', 'woman', 'wonder', 'wonderful', 'wood', 'wooden', 'wool',
  'word', 'work', 'worker', 'working', 'workshop', 'world', 'worldwide', 'worry', 'worse', 'worst',
  'worth', 'would', 'write', 'writer', 'writing', 'wrong', 'yard', 'yeah', 'year', 'yellow',
  'yes', 'yesterday', 'yet', 'yield', 'young', 'your', 'yourself', 'youth', 'zone'
]);

export function isLevel4Word(word: string): boolean {
  return LEVEL_4_VOCABULARY.has(word.toLowerCase());
}

export function validateLevel4Sentence(sentence: string, userName?: string): { 
  isValid: boolean; 
  invalidWords: string[];
} {
  const words = sentence.toLowerCase()
    .replace(/[^\w\s]/g, '') // Remove punctuation
    .split(/\s+/)
    .filter(word => word.length > 0);
  
  const userNameLower = userName?.toLowerCase();
  const invalidWords = words.filter(word => {
    // Always allow the user's name
    if (userNameLower && word === userNameLower) {
      return false;
    }
    return !LEVEL_4_VOCABULARY.has(word);
  });
  
  return {
    isValid: invalidWords.length === 0,
    invalidWords
  };
}