// Level 0 Templates - 100% Vocabulary Compliant with Enhanced Level 0 Vocabulary
// All words from ENHANCED_LEVEL_0_VOCABULARY only (100 words total)
// Simple 1-sentence per page structure for ages 3-5

export const VOCABULARY_COMPLIANT_LEVEL_0_TEMPLATES: string[][] = [
  ["{userName} can run.", "Run fast.", "Run to me.", "Good job!", "Play time now.", "Run again!"],
  ["{userName} has ball.", "Ball is {favoriteColor}.", "Throw the ball.", "Catch it!", "Ball game fun.", "Play more!"],
  ["{userName} sees cat.", "Cat says meow.", "Pet the cat.", "Cat is soft.", "Cat likes you.", "Good cat!"],
  ["{userName} eats food.", "Food is good.", "Yum yum yum.", "All done.", "Good eating.", "More please!"],
  ["{userName} can jump.", "Jump up high.", "Jump down low.", "Jump jump jump.", "Jumping fun.", "Jump again!"],
  ["{userName} has toy.", "Toy is {favoriteColor}.", "Play with toy.", "Fun to play.", "Toy time.", "Put away!"],
  ["{userName} sees dog.", "Dog says woof.", "Pat the dog.", "Dog is nice.", "Dog wags tail.", "Good dog!"],
  ["{userName} can walk.", "Walk to park.", "Walk walk walk.", "See nice things.", "Walking fun.", "Walk home!"],
  ["{userName} has book.", "Look at book.", "See the pictures.", "Stories fun.", "Read more.", "Books good!"],
  ["{userName} sees bird.", "Bird can fly.", "Bird sings song.", "Pretty bird.", "Fly away bird.", "Bye bye!"],
  ["{userName} can swim.", "Water is fun.", "Splash splash splash.", "Swim like fish.", "Water play.", "Swim more!"],
  ["{userName} has bike.", "Bike is {favoriteColor}.", "Ride the bike.", "Go fast.", "Bike fun.", "Stop now!"],
  ["{userName} sees tree.", "Tree is big.", "Leaves are green.", "Climb the tree.", "Tree fun.", "Come down!"],
  ["{userName} can sing.", "La la la.", "Songs are nice.", "Sing loud.", "Music fun.", "Sing more!"],
  ["{userName} has hat.", "Hat is {favoriteColor}.", "Put on hat.", "Hat fits good.", "Look nice.", "Wear hat!"],
  ["{userName} sees sun.", "Sun is bright.", "Sun is warm.", "Feel the sun.", "Sun good.", "Sunny day!"],
  ["{userName} can dance.", "Move and shake.", "Dance dance dance.", "Music plays.", "Dancing fun.", "Dance more!"],
  ["{userName} has cup.", "Cup is {favoriteColor}.", "Drink from cup.", "Water good.", "All done.", "Put down!"],
  ["{userName} sees flower.", "Flower pretty.", "Smell the flower.", "Nice smell.", "Flower good.", "Pick one!"],
  ["{userName} can clap.", "Clap clap clap.", "Hands make noise.", "Clapping fun.", "Clap loud.", "Good job!"],
  ["{userName} has shoes.", "Shoes are {favoriteColor}.", "Put on shoes.", "Walk in shoes.", "Shoes fit.", "Good shoes!"],
  ["{userName} sees moon.", "Moon is bright.", "Moon at night.", "Look at moon.", "Moon pretty.", "Night time!"],
  ["{userName} can laugh.", "Ha ha ha.", "Laughing fun.", "Laugh loud.", "Feel happy.", "Laugh more!"],
  ["{userName} has spoon.", "Spoon helps eat.", "Scoop the food.", "Eat it up.", "Spoon good.", "All clean!"],
  ["{userName} sees star.", "Star twinkles.", "Star far away.", "Make a wish.", "Star bright.", "Night sky!"],
  ["{userName} has crayon.", "Crayon {favoriteColor}.", "Draw picture.", "Make art.", "Pretty colors.", "Draw more!"],
  ["{userName} sees bus.", "Bus is big.", "Bus goes beep.", "Ride the bus.", "Bus fun.", "Get off!"],
  ["{userName} can hop.", "Hop on one foot.", "Hop hop hop.", "Like a bunny.", "Hopping fun.", "Hop more!"],
  ["{userName} has blocks.", "Blocks stack up.", "Build tower.", "Make it tall.", "Blocks fun.", "Build more!"],
  ["{userName} sees rain.", "Rain falls down.", "Wet and cool.", "Splash in puddles.", "Rain fun.", "Stay dry!"],
  ["{userName} can skip.", "Skip skip skip.", "Like to skip.", "Skip to park.", "Skipping fun.", "Skip home!"],
  ["{userName} has bear.", "Bear is soft.", "Hug the bear.", "Bear friend.", "Sleep with bear.", "Good bear!"],
  ["{userName} sees truck.", "Truck is big.", "Truck works hard.", "Beep beep truck.", "Truck strong.", "Go truck!"],
  ["{userName} can roll.", "Roll on grass.", "Roll down hill.", "Roll roll roll.", "Rolling fun.", "Roll more!"],
  ["{userName} has juice.", "Juice tastes good.", "Drink it up.", "Yummy juice.", "All done.", "More please!"],
  ["{userName} sees horse.", "Horse runs fast.", "Horse says neigh.", "Pet the horse.", "Horse nice.", "Ride horse!"],
  ["{userName} can crawl.", "Crawl like baby.", "Crawl crawl crawl.", "On hands and knees.", "Crawling fun.", "Stand up!"],
  ["{userName} has water.", "Water is cool.", "Drink the water.", "Thirsty no more.", "Water good.", "All done!"],
  ["{userName} sees snow.", "Snow is white.", "Soft and cold.", "Make snowball.", "Snow fun.", "Winter play!"],
  ["{userName} can catch.", "Throw to me.", "Catch the ball.", "Good catching.", "Play catch.", "Fun game!"],
  ["{userName} has apple.", "Apple is red.", "Bite the apple.", "Sweet and good.", "Apple yummy.", "Eat more!"],
  ["{userName} sees frog.", "Frog says ribbit.", "Frog can jump.", "Green and small.", "Frog hops.", "Bye frog!"],
  ["{userName} can hide.", "Hide and seek.", "Where is {userName}?", "Found you!", "Hiding fun.", "Play more!"],
  ["{userName} has drum.", "Drum makes noise.", "Bang bang bang.", "Music loud.", "Drum fun.", "Play song!"],
  ["{userName} sees cake.", "Cake looks good.", "Sweet and nice.", "Take a bite.", "Cake yummy.", "Happy day!"],
  ["{userName} can help.", "Help mom cook.", "Stir the pot.", "Good helper.", "Help is nice.", "Thank you!"],
  ["{userName} has fish.", "Fish swims fast.", "In the water.", "Pretty fish.", "Fish happy.", "Swim more!"],
  ["{userName} sees ant.", "Ant is small.", "Ant works hard.", "Carry big load.", "Ant strong.", "Good ant!"],
  ["{userName} can blow.", "Blow out candles.", "Make a wish.", "Puff puff puff.", "Candles out.", "Wish time!"],
  ["{userName} has tent.", "Tent for camping.", "Sleep outside.", "Under stars.", "Tent cozy.", "Camp fun!"],
  ["{userName} sees wind.", "Wind blows trees.", "Leaves dance.", "Feel the breeze.", "Wind nice.", "Windy day!"],
  ["{userName} can fix.", "Fix the toy.", "Make it work.", "All better now.", "Fixing fun.", "Good job!"],
  ["{userName} has soap.", "Soap makes bubbles.", "Wash hands clean.", "Bubbles pop.", "Soap good.", "All clean!"],
  ["{userName} sees nest.", "Bird made nest.", "Baby birds inside.", "Chirp chirp chirp.", "Nest safe.", "Bird family!"],
  ["{userName} can wait.", "Wait your turn.", "Be patient.", "Turn is here.", "Waiting good.", "Your turn!"],
  ["{userName} has bell.", "Bell rings loud.", "Ding dong ding.", "Pretty sound.", "Bell music.", "Ring more!"],
  ["{userName} sees bee.", "Bee makes honey.", "Buzz buzz buzz.", "Yellow and black.", "Bee works.", "Busy bee!"],
  ["{userName} can share.", "Share with friends.", "Give some too.", "Sharing nice.", "Friends happy.", "Share more!"],
  ["{userName} has key.", "Key opens door.", "Turn the lock.", "Door opens wide.", "Key works.", "Come in!"],
  ["{userName} sees owl.", "Owl says hoot.", "Big round eyes.", "Flies at night.", "Owl wise.", "Night bird!"],
  ["{userName} can kiss.", "Kiss goodnight.", "Sweet dreams.", "Love you lots.", "Kiss soft.", "Sleep tight!"],
  ["{userName} has rope.", "Rope is long.", "Jump the rope.", "Up and down.", "Rope fun.", "Jump more!"],
  ["{userName} sees waves.", "Waves crash down.", "Water moves.", "Beach is fun.", "Waves big.", "Splash splash!"],
  ["{userName} can peek.", "Peek around corner.", "What do you see?", "Something fun!", "Peeking fun.", "Look more!"],
  ["{userName} has map.", "Map shows way.", "Follow the path.", "Find the place.", "Map helps.", "Good guide!"],
  ["{userName} sees gem.", "Gem sparkles bright.", "Pretty colors.", "Shiny and nice.", "Gem beautiful.", "Keep safe!"],
  ["{userName} can hug.", "Hug mom tight.", "Arms around.", "Feel the love.", "Hugs warm.", "Love you!"],
  ["{userName} has bow.", "Bow is pretty.", "Tie in hair.", "Look so nice.", "Bow cute.", "Pretty bow!"],
  ["{userName} sees path.", "Path goes far.", "Walk this way.", "Follow along.", "Path leads.", "Keep going!"],
  ["{userName} can wink.", "Wink one eye.", "Fun to do.", "Wink at friends.", "Winking fun.", "Wink more!"],
  ["{userName} has coin.", "Coin is round.", "Shiny and gold.", "Make a wish.", "Coin lucky.", "Keep it!"],
  ["{userName} sees door.", "Door is closed.", "Knock knock knock.", "Someone home?", "Door opens.", "Come in!"],
  ["{userName} can nod.", "Nod your head.", "Yes yes yes.", "Up and down.", "Nodding means yes.", "Good job!"],
  ["{userName} has yarn.", "Yarn is soft.", "Wind it up.", "Make a ball.", "Yarn nice.", "Keep winding!"],
  ["{userName} sees hill.", "Hill is tall.", "Climb to top.", "See far away.", "Hill high.", "Great view!"],
  ["{userName} can point.", "Point at things.", "Use your finger.", "Show me that.", "Pointing helps.", "Point more!"],
  ["{userName} has box.", "Box holds things.", "Put toys inside.", "Close the lid.", "Box full.", "All away!"],
  ["{userName} sees pond.", "Pond has water.", "Ducks swim here.", "Water still.", "Pond nice.", "Pretty water!"],
  ["{userName} can wave.", "Wave goodbye.", "Move your hand.", "See you later.", "Waving nice.", "Bye bye!"],
  ["{userName} has mask.", "Mask for face.", "Pretend play.", "Who are you?", "Mask fun.", "Play pretend!"],
  ["{userName} sees clock.", "Clock tells time.", "Tick tock tick.", "What time now?", "Clock works.", "Time goes!"],
  ["{userName} can turn.", "Turn around.", "Spin and spin.", "Feel dizzy?", "Turning fun.", "Spin more!"],
  ["{userName} has shell.", "Shell from beach.", "Ocean made it.", "Pretty shape.", "Shell keeps.", "Beach memory!"],
  ["{userName} sees flag.", "Flag waves high.", "Red white blue.", "Wind makes dance.", "Flag pretty.", "Proud flag!"],
  ["{userName} can bend.", "Bend down low.", "Touch your toes.", "Stretch and reach.", "Bending good.", "Stretch more!"],
  ["{userName} has seed.", "Seed will grow.", "Plant in dirt.", "Water each day.", "Seed grows.", "Plant comes!"],
  ["{userName} sees light.", "Light is bright.", "Chase darkness away.", "See things clear.", "Light good.", "Bright day!"],
  ["{userName} can count.", "One two three.", "Count to ten.", "Numbers fun.", "Counting good.", "Count more!"],
  ["{userName} has stick.", "Stick from tree.", "Draw in sand.", "Make pictures.", "Stick draws.", "Art in sand!"],
  ["{userName} sees shadow.", "Shadow follows you.", "Dark shape moves.", "Fun to chase.", "Shadow friend.", "Play shadow!"],
  ["{userName} can taste.", "Taste the food.", "Sweet or sour?", "Yummy flavors.", "Tasting fun.", "Taste more!"],
  ["{userName} has crown.", "Crown for king.", "Wear on head.", "Feel royal.", "Crown fits.", "King {userName}!"],
  ["{userName} sees smoke.", "Smoke goes up.", "Gray and wispy.", "Fire makes it.", "Smoke rises.", "Up it goes!"],
  ["{userName} can knock.", "Knock on door.", "Tap tap tap.", "Someone there?", "Knocking calls.", "Answer door!"],
  ["{userName} has wheel.", "Wheel rolls round.", "Turn and turn.", "Makes things move.", "Wheel helps.", "Round and round!"],
  ["{userName} sees mirror.", "Mirror shows you.", "Look at self.", "Wave to you.", "Mirror fun.", "Hello there!"],
  ["{userName} can smell.", "Smell the flowers.", "Sniff sniff sniff.", "Sweet smells nice.", "Smelling good.", "Smell more!"],
  ["{userName} has bag.", "Bag holds things.", "Carry with you.", "Pack it full.", "Bag helps.", "Carry along!"],
  ["{userName} sees bridge.", "Bridge crosses water.", "Walk across.", "Over we go.", "Bridge strong.", "Safe crossing!"],
  ["{userName} can listen.", "Listen with ears.", "Hear the sounds.", "Music plays.", "Listening good.", "Hear more!"],
  ["{userName} has ring.", "Ring goes round.", "Wear on finger.", "Shiny band.", "Ring pretty.", "Sparkles bright!"],
  ["{userName} sees tower.", "Tower is tall.", "Built up high.", "Blocks stacked.", "Tower strong.", "Build more!"],
  ["{userName} can feel.", "Feel with hands.", "Soft or rough?", "Touch and learn.", "Feeling tells.", "Touch more!"],
  ["{userName} has chain.", "Chain links together.", "Strong connection.", "Hold things tight.", "Chain works.", "Links connect!"],
  ["{userName} sees garden.", "Garden grows things.", "Flowers and food.", "Pretty colors.", "Garden nice.", "Plants grow!"],
  ["{userName} can remember.", "Remember the fun.", "Think back.", "Good times.", "Memory keeps.", "Don't forget!"],
  ["{userName} has pocket.", "Pocket holds things.", "Keep treasures safe.", "Special place.", "Pocket helps.", "Safe keeping!"],
  ["{userName} sees rainbow.", "Rainbow has colors.", "After the rain.", "Pretty arc.", "Rainbow magic.", "Colors bright!"],
  ["{userName} can wonder.", "Wonder about things.", "Ask questions.", "Think and learn.", "Wondering good.", "Keep asking!"],
  ["{userName} has ticket.", "Ticket for ride.", "Show to get on.", "Special paper.", "Ticket works.", "Ride time!"],
  ["{userName} sees castle.", "Castle is big.", "Kings lived there.", "Tall stone walls.", "Castle strong.", "Old and grand!"],
  ["{userName} can dream.", "Dream at night.", "Fun adventures.", "While you sleep.", "Dreams come.", "Sweet dreams!"]
];

export function getVocabularyCompliantLevel0Template(): string[] {
  const randomIndex = Math.floor(Math.random() * VOCABULARY_COMPLIANT_LEVEL_0_TEMPLATES.length);
  return VOCABULARY_COMPLIANT_LEVEL_0_TEMPLATES[randomIndex];
}

export function getVocabularyCompliantLevel0TemplateCount(): number {
  return VOCABULARY_COMPLIANT_LEVEL_0_TEMPLATES.length;
}

export function getAllVocabularyCompliantLevel0Templates(): string[][] {
  return VOCABULARY_COMPLIANT_LEVEL_0_TEMPLATES;
}