import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

// TypeScript type imports
import type { UserInfo } from "../_shared/types/index.ts";

// ============= PERFECT AI VISUAL SCENE CREATOR WITH CHARACTER CONSISTENCY =============
// Complete implementation with word-for-word OpenAI prompts and CharacterConsistencyService integration

// CORS headers for cross-origin requests
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Character consistency service integration
let characterService: any = null;

async function getCharacterService() {
  if (!characterService) {
    try {
      const { CharacterConsistencyService } = await import('../_shared/CharacterConsistencyService.js');
      characterService = CharacterConsistencyService.getInstance();
    } catch (error) {
      console.warn('Failed to load CharacterConsistencyService:', error);
      // Create minimal fallback service
      characterService = {
        analyzeVisualDetails: async () => {},
        detectSecondaryCharacters: async () => [],
        getSecondaryCharacterSeed: async () => ({ seed: Math.floor(Math.random() * 999999) }),
        getCharacterAppearanceFromStory: async () => '',
        getColoredObjects: async () => '',
        clearSession: async () => {}
      };
    }
  }
  return characterService;
}

// Generate complete visual schema using OpenAI with word-for-word prompts
async function generateCompleteVisualSchema(storyText: string, userInfo: any, sessionId: string, pageNumber: number = 1) {
  const openaiApiKey = Deno.env.get('OPENAI_API_KEY');
  if (!openaiApiKey) {
    throw new Error('OPENAI_API_KEY not configured');
  }

  // CHARACTER CONSISTENCY INTEGRATION - Phase 2
  const characterService = await getCharacterService();
  const characterName = userInfo?.name || userInfo?.userName || 'child';

  // Analyze visual details for character consistency
  await characterService.analyzeVisualDetails(sessionId, storyText, pageNumber, characterName);

  // Detect secondary characters  
  const detectedCharacters = await characterService.detectSecondaryCharacters(sessionId, storyText, pageNumber);

  // Get colored objects for scene consistency
  const coloredObjects = await characterService.getColoredObjects(sessionId);

  // Get character appearance from story
  const characterAppearance = await characterService.getCharacterAppearanceFromStory(sessionId, characterName);

  // WORD-FOR-WORD OpenAI PROMPTS - Phase 1
  const systemPrompt = "You are an expert scene analyzer that generates structured visual descriptions for children's story illustrations. ALWAYS return valid JSON with this exact structure: {primaryScene, backgroundColor, lighting, composition, setting, mood, style, secondaryCharacters, objects}";

  const userPrompt = `Analyze this story text and return a JSON object with: primaryScene (main scene description), backgroundColor (dominant background color/theme), lighting (lighting conditions), composition (visual arrangement), setting (location/environment), mood (emotional atmosphere), style (visual style), secondaryCharacters (array of other characters), objects (array of key objects/props). Story text: ${storyText}`;

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openaiApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-5-mini-2025-08-07',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_completion_tokens: 500,
      }),
    });

    if (!response.ok) {
      throw new Error(`OpenAI API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content?.trim();
    
    if (!content) {
      throw new Error('No content generated by OpenAI');
    }

    // Parse JSON response
    let visualSchema;
    try {
      visualSchema = JSON.parse(content);
    } catch (parseError) {
      console.warn('Failed to parse OpenAI JSON response, extracting manually:', parseError);
      // Fallback extraction if JSON parsing fails
      visualSchema = {
        primaryScene: content.substring(0, 200),
        backgroundColor: 'bright and colorful',
        lighting: 'warm natural lighting',
        composition: 'character-focused',
        setting: 'indoor scene',
        mood: 'cheerful and engaging',
        style: 'children\'s book illustration',
        secondaryCharacters: [],
        objects: []
      };
    }

    // Enhance with character consistency data
    const enhancedSchema = {
      ...visualSchema,
      // Merge detected secondary characters
      secondaryCharacters: [
        ...(visualSchema.secondaryCharacters || []),
        ...detectedCharacters.map((char: any) => char.name)
      ],
      // Merge detected objects with colored objects
      objects: [
        ...(visualSchema.objects || []),
        ...coloredObjects.split(',').map((obj: string) => obj.trim()).filter(Boolean)
      ],
      // Add character appearance if available
      characterAppearance: characterAppearance || '',
      // Add consistency metadata
      detectedCharacters,
      coloredObjects
    };

    console.log('✅ Generated complete visual schema with character consistency');
    return enhancedSchema;

  } catch (error) {
    console.error('OpenAI generation failed:', error);
    
    // Fallback schema generation
    const fallbackSchema = {
      primaryScene: `${characterName} in a beautiful story scene from: ${storyText.substring(0, 100)}`,
      backgroundColor: 'bright and colorful',
      lighting: 'warm natural lighting',
      composition: 'character-focused composition',
      setting: 'story setting',
      mood: 'cheerful and engaging',
      style: 'children\'s book illustration',
      secondaryCharacters: detectedCharacters.map((char: any) => char.name),
      objects: coloredObjects.split(',').map((obj: string) => obj.trim()).filter(Boolean),
      characterAppearance: characterAppearance || '',
      detectedCharacters,
      coloredObjects
    };

    console.log('⚠️ Using fallback visual schema');
    return fallbackSchema;
  }
}

// Generate character seed with consistency service
async function generateCharacterSeed(sessionId: string, userInfo: any) {
  const characterService = await getCharacterService();
  const characterName = userInfo?.name || userInfo?.userName || 'child';
  
  try {
    // Generate secondary character seed using CharacterConsistencyService
    const secondaryData = await characterService.getSecondaryCharacterSeed(
      sessionId, 
      characterName, 
      'secondary_character'
    );

    return {
      seed: secondaryData.seed || Math.floor(Math.random() * 999999),
      characterName,
      avatarType: userInfo?.avatar?.type || 'child',
      skinTone: userInfo?.avatar?.skinTone || userInfo?.skinTone || 'medium',
      culturalProfile: userInfo?.nativeLanguage !== 'en' ? userInfo?.nativeLanguage : undefined
    };
  } catch (error) {
    console.warn('Character seed generation failed, using fallback:', error);
    return {
      seed: Math.floor(Math.random() * 999999),
      characterName,
      avatarType: userInfo?.avatar?.type || 'child',
      skinTone: userInfo?.avatar?.skinTone || userInfo?.skinTone || 'medium'
    };
  }
}

// Call runware-template-cd for Direct Mode image generation
async function callRunwareTemplateCD(payload: any): Promise<string> {
  try {
    const response = await fetch('https://cpzeuogomaixamrtnnmj.supabase.co/functions/v1/runware-template-cd', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')}`
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      throw new Error(`runware-template-cd failed: ${response.status} ${response.statusText}`);
    }

    const result = await response.json();
    
    if (!result.success || !result.imageURL) {
      throw new Error(`runware-template-cd failed: ${result.error || 'No image URL returned'}`);
    }

    return result.imageURL;
  } catch (error) {
    console.error('Direct Mode image generation failed:', error);
    throw error;
  }
}

// HTTP fallback for Supabase client failures
async function httpFallbackCall(endpoint: string, payload: any): Promise<any> {
  const supabaseUrl = Deno.env.get('SUPABASE_URL');
  const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  
  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error('Missing Supabase configuration for HTTP fallback');
  }

  const response = await fetch(`${supabaseUrl}/functions/v1/${endpoint}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${serviceRoleKey}`
    },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    throw new Error(`HTTP fallback failed: ${response.status} ${response.statusText}`);
  }

  return await response.json();
}

// Main request handler
serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  // Health check endpoints
  if (req.method === 'HEAD' && req.url.includes('/health')) {
    return new Response(null, { 
      status: 200, 
      headers: corsHeaders 
    });
  }

  if (req.method === 'GET') {
    return new Response(JSON.stringify({ 
      status: 'healthy', 
      service: 'ai-visual-scene-creator',
      timestamp: new Date().toISOString()
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }

  // Only allow POST for main functionality
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), {
      status: 405,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }

  try {
    const requestId = `${Math.random().toString(36).substring(2)}`;
    console.log(`🚀 [${requestId}] ai-visual-scene-creator: POST ${req.url}`);

    // Parse request payload
    let payload: any;
    try {
      payload = await req.json();
    } catch (error) {
      console.error(`❌ [${requestId}] Failed to parse JSON:`, error);
      return new Response(JSON.stringify({
        success: false,
        error: 'Invalid JSON payload'
      }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Validate required fields
    const storyText = payload.pageText || payload.storyText;
    if (!storyText) {
      console.error(`❌ [${requestId}] Validation failure (no retry): MISSING_STORY_CONTENT`);
      return new Response(JSON.stringify({
        success: false,
        error: 'MISSING_STORY_CONTENT',
        tier: 'VALIDATION_FAILED'
      }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const userInfo = payload.userInfo || {};
    const sessionId = payload.sessionId || `session-${requestId}`;
    const pageNumber = payload.pageNumber || 1;
    const directMode = payload.directMode === true;

    console.log(`✅ [${requestId}] Payload validated - Direct Mode: ${directMode}`);

    // PHASE 1 & 2: Generate complete visual schema with character consistency
    console.log(`🎨 [${requestId}] Generating complete visual schema...`);
    const visualSchema = await generateCompleteVisualSchema(storyText, userInfo, sessionId, pageNumber);

    // Generate character seed for consistency
    const characterSeed = await generateCharacterSeed(sessionId, userInfo);

    // Create cultural bundle
    const culturalBundle = {
      hair: userInfo?.avatar?.hairColor || 'brown hair',
      features: userInfo?.nativeLanguage !== 'en' ? `${userInfo.nativeLanguage} cultural features` : 'diverse features',
      profile: characterSeed.culturalProfile
    };

    // Get colored objects string
    const coloredObjects = visualSchema.coloredObjects || '';

    // PHASE 3: Handle Direct Mode vs Scene-Only Mode
    let imageURL: string | undefined;
    let tier: string;

    if (directMode) {
      console.log(`🖼️ [${requestId}] Direct Mode: Generating image via runware-template-cd`);
      
      // Prepare payload for runware-template-cd
      const templatePayload = {
        pageText: storyText,
        userInfo,
        sessionId,
        pageNumber,
        avatarIdentity: {
          type: characterSeed.avatarType,
          skinTone: characterSeed.skinTone,
          name: characterSeed.characterName
        },
        templateComplexity: 'C', // Use Tier 2.5C for nuclear hardcoded template
        failedTierData: {
          enhancedSceneData: visualSchema.primaryScene,
          characterConsistency: `${characterSeed.characterName} (${characterSeed.avatarType})`,
          visualConsistency: `${visualSchema.backgroundColor}, ${visualSchema.lighting}`,
          culturalEnhancements: culturalBundle.hair
        }
      };

      try {
        imageURL = await callRunwareTemplateCD(templatePayload);
        tier = 'DIRECT_MODE';
        console.log(`✅ [${requestId}] Direct Mode image generated successfully`);
      } catch (directError) {
        console.error(`❌ [${requestId}] Direct Mode failed, falling back to Scene-Only:`, directError);
        // Fall back to Scene-Only mode if Direct Mode fails
        tier = 'TIER_1_SCENE_ONLY';
      }
    } else {
      console.log(`📋 [${requestId}] Scene-Only Mode: Returning schema for orchestrator`);
      tier = 'TIER_1_SCENE_ONLY';
    }

    // PHASE 4: Return complete orchestrator-expected schema
    const response = {
      success: true,
      tier,
      // Core visual schema from OpenAI
      primaryScene: visualSchema.primaryScene,
      enhancedPrompt: visualSchema.primaryScene, // enhancedPrompt = primaryScene for orchestrator
      negativePrompt: 'blurry, low quality, dark, scary, violent, inappropriate, adult content, text, watermarks',
      backgroundColor: visualSchema.backgroundColor,
      lighting: visualSchema.lighting,
      composition: visualSchema.composition,
      setting: visualSchema.setting,
      mood: visualSchema.mood,
      style: visualSchema.style,
      secondaryCharacters: visualSchema.secondaryCharacters || [],
      objects: visualSchema.objects || [],
      
      // Character consistency data
      characterSeed,
      culturalBundle,
      coloredObjects,
      
      // Metadata for orchestrator
      templateStructure: 'COMPLETE_TIER_1',
      detectedCharacters: visualSchema.detectedCharacters || [],
      
      // Image URL only in Direct Mode
      ...(imageURL && { imageURL }),
      
      // Processing metadata
      requestId,
      timestamp: new Date().toISOString(),
      processingTime: Date.now()
    };

    console.log(`✅ [${requestId}] Response prepared:`, {
      tier: response.tier,
      hasPrimaryScene: !!response.primaryScene,
      hasImageURL: !!response.imageURL,
      secondaryCharacterCount: response.secondaryCharacters.length,
      objectCount: response.objects.length
    });

    return new Response(JSON.stringify(response), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    console.error('ai-visual-scene-creator error:', errorMessage);
    
    return new Response(JSON.stringify({
      success: false,
      error: errorMessage,
      tier: 'ERROR'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});