// Robust Two-Tier Story Template System
// Free Trial: Enhanced template pool | Premium: Ultra-robust infinite variety

export interface TemplateSystem {
  free: {
    easy: string[][];
    medium: string[][];
    hard: string[][];
    expert: string[][];
  };
  premium: {
    easy: string[][];
    medium: string[][];
    hard: string[][];
    expert: string[][];
  };
}

// FREE TIER - Enhanced Robust System (25+ Easy, 20+ Medium, 15+ Hard, 12+ Expert)
const FREE_TIER_TEMPLATES = {
  easy: [
    // Original templates (1-8) maintained for consistency
    ["{name} sees a {animal}", "The {animal} is {color}", "{name} says hello", "They play ball", "The {animal} runs fast", "{name} runs too", "They have fun", "{name} likes the {animal}", "They are friends", "{name} is happy"],
    ["{name} goes out", "{pronoun} finds a {object}", "The {object} is {color}", "{name} picks it up", "A {animal} comes", "It wants the {object}", "{name} gives it", "The {animal} is happy", "They play together", "{name} feels good"],
    ["{name} sees a {animal}", "The {animal} looks sad", "It lost its {food}", "{name} wants to help", "They look and look", "{name} finds the {food}", "It was under rocks", "{name} gives it back", "The {animal} is happy", "They are good friends"],
    ["{name} has a {object}", "It is {color}", "A {animal} comes", "It wants to play", "{name} lets it play", "They play together", "The {animal} is happy", "{name} is happy too", "They play all day", "Good friends share"],
    ["{name} goes outside", "The sun is bright", "A {animal} waves hello", "They walk together", "{name} sees pretty flowers", "The {animal} smells them", "They sit and rest", "{name} feels happy", "The {animal} does too", "What a good day"],
    ["{name} looks around", "Something is hiding", "A {color} {animal} appears", "It looks very shy", "{name} sits down", "The {animal} comes close", "They look at each other", "{name} smiles big", "The {animal} smiles too", "New friends are nice"],
    ["{name} sees a {animal}", "It looks very sad", "It lost its {food}", "{name} wants to help", "They look together", "The {food} is here", "{name} gives it back", "The {animal} is happy", "They hug gently", "Helping feels good"],
    ["{name} tries something new", "A {animal} shows how", "First it is hard", "{name} tries again", "The {animal} helps", "Now it is fun", "{name} can do it", "They both feel proud", "Learning is great", "Practice makes perfect"],

    // NEW Enhanced Templates (9-25) - Level 1 vocabulary only
    ["{name} wakes up", "The sun is up", "A {animal} says hi", "They eat {food}", "It tastes good", "{name} feels strong", "The {animal} smiles", "They go play", "Fun all day", "Sleep time now"],
    ["{name} finds a box", "It is {color}", "What is in it", "A tiny {animal}", "It needs help", "{name} is kind", "They make it safe", "It grows big", "Now it can help", "Friends help friends"],
    ["{name} plants a seed", "Water goes on", "Sun makes it warm", "A green plant grows", "It gets bigger", "A {animal} comes", "It likes the plant", "{name} feels proud", "Growing is fun", "Care makes things grow"],
    ["{name} hears music", "A {animal} sings", "The song is nice", "{name} sings too", "They make music", "Other {animal}s come", "Everyone sings", "Music brings joy", "Happy sounds", "Songs make friends"],
    ["{name} draws a picture", "It shows a {animal}", "The {animal} is {color}", "Art is fun", "A real {animal} sees", "It likes the picture", "{name} feels happy", "Art shows love", "Create and share", "Pictures tell stories"],
    ["{name} bakes {food}", "It smells good", "A {animal} comes", "It wants some", "{name} shares", "They eat together", "Sweet and good", "Food tastes better", "When shared", "Cook with love"],
    ["{name} builds a house", "It is for {animal}s", "Small but cozy", "The {animal}s come", "They love it", "{name} feels good", "Building helps", "Homes keep safe", "Care for others", "Build with love"],
    ["{name} reads a book", "Pictures are pretty", "A {animal} listens", "Stories are fun", "They learn new things", "Books teach us", "{name} loves reading", "Words make pictures", "Read and grow", "Stories connect us"],
    ["{name} goes swimming", "Water feels nice", "A {animal} swims too", "They splash and play", "Water is fun", "They race each other", "{name} swims fast", "Exercise feels good", "Play in water", "Swimming is healthy"],
    ["{name} climbs a tree", "Up high up", "A {animal} lives there", "It shows the view", "Pretty things below", "Sky is close", "{name} feels brave", "Climbing is fun", "See the world", "Heights show beauty"],
    ["{name} makes a friend", "New {animal} is shy", "They play slowly", "Trust grows big", "They share {food}", "Fun games together", "{name} feels happy", "Friends are special", "Be kind always", "Friendship grows"],
    ["{name} loses a toy", "Feels very sad", "A {animal} helps look", "They search everywhere", "Find it at last", "Under a bush", "{name} feels joy", "Friends help always", "Never give up", "Help makes stronger"],
    ["{name} paints the fence", "Brush up and down", "A {animal} helps too", "Work goes faster", "They paint it {color}", "Pretty and new", "{name} feels proud", "Work together", "Jobs are easier", "Together is better"],
    ["{name} feeds the {animal}s", "They are hungry", "Food makes them happy", "They eat well", "Grow big and strong", "{name} cares much", "Love shows in care", "Feed with kindness", "Care makes love", "Love feeds all"],
    ["{name} takes a walk", "Pretty day outside", "A {animal} walks too", "They see nice things", "Flowers and trees", "Birds sing songs", "{name} feels peaceful", "Nature is pretty", "Walk and see", "Beauty is everywhere"],
    ["{name} makes a gift", "For a special {animal}", "Made with love", "Time and care", "The {animal} loves it", "Hugs for {name}", "Giving feels good", "Love in making", "Gifts show care", "Love gives joy"]
  ],

  medium: [
    // Original templates (1-5) maintained for consistency
    ["{name} finds a special {setting} today", "A nice {animal} lives there happily", "The {animal} can talk to {name}", "It tells {name} some fun stories", "A pretty {object} waits for them", "It has some special magic powers", "{name} must find it very soon", "They look through the big forest", "Together they help solve the problem", "This fun trip teaches {name} about friendship"],
    ["The {setting} has a big problem today", "All the {primary_animal}s lost their {primary_food}", "{name} wants to help them right away", "{pronoun} meets a very helpful {secondary_animal}", "They work together as a good team", "The {secondary_animal} shows {name} a secret path", "They find where the {primary_food} is hiding", "A silly {friend_animal} took it for fun", "{name} tells why sharing is very important", "Everyone learns the lesson and becomes friends"],
    ["{name} finds a magical {object} in the garden", "When touched, it glows with {color} light", "A wise {animal} appears from the forest", "It explains the {object} has special powers", "{name} must learn to use it carefully", "The first lesson is about being kind", "The {animal} teaches {name} important magical words", "Together they practice using the power properly", "{name} helps solve problems in the neighborhood", "Magic works best when shared with friends"],
    ["{name} decides to explore the mysterious forest", "The trees whisper secrets in the wind", "A friendly {animal} offers to be guide", "They discover a hidden clearing with flowers", "In the center grows a beautiful tree", "The tree bears fruit that changes colors", "{name} learns each color has special meaning", "Red means courage, blue means peace", "The {animal} explains these are wisdom fruits", "{name} takes one lesson back home"],
    ["{name} builds a small boat by the shore", "A clever {animal} asks to join adventure", "They sail together across the sparkling water", "Strange and wonderful islands appear everywhere", "Each island has a different amazing surprise", "One has singing flowers, another dancing trees", "The {animal} knows stories about each place", "{name} learns that adventures are more fun", "When shared with a good friend nearby", "They promise to explore more together soon"],

    // NEW Enhanced Templates (6-20) - 5-9 words per page
    ["{name} discovers a secret garden behind the house", "Colorful butterflies dance around the beautiful flowers", "A talking {animal} welcomes {name} to this place", "The garden has been waiting for someone kind", "Every flower here tells a different story", "Some stories are about courage and friendship", "{name} listens carefully to each magical tale", "The {animal} teaches {name} about plant languages", "Together they help flowers that look sad", "The garden blooms brighter because of their care"],
    ["{name} finds an old map in the attic", "It shows a path to a treasure", "A wise {animal} explains the map's secrets", "The treasure isn't gold or silver coins", "It's something much more valuable than money", "The journey teaches lessons about being brave", "Each challenge helps {name} grow stronger inside", "The {animal} guides through difficult moments carefully", "At the end, {name} discovers the real treasure", "The treasure was the friendship made along way"],
    ["{name} starts a neighborhood book club for kids", "Every week they meet under the big tree", "A scholarly {animal} joins their reading group", "They read stories from around the world", "Each book teaches about different cultures and places", "The {animal} shares stories from its travels", "{name} learns that books connect all people", "Reading together makes stories even more special", "The club grows as more friends join", "Books build bridges between different kinds of people"],
    ["{name} organizes a community garden for everyone", "Neighbors bring seeds from their favorite plants", "A gardening {animal} teaches proper planting techniques", "Everyone works together preparing the rich soil", "Children and adults plant vegetables and flowers", "The {animal} shows how plants help each other", "Weeks pass and the garden grows beautifully", "People share the harvest with their neighbors", "{name} sees how cooperation creates abundance", "The garden brings the whole community together"],
    ["{name} learns to play a musical instrument", "A talented {animal} becomes the patient teacher", "At first the sounds are squeaky and strange", "Practice every day makes the music better", "The {animal} shows how music tells stories", "Different notes can express various emotions clearly", "{name} practices songs from many different countries", "Music becomes a way to share feelings", "Other children want to learn music too", "Together they form a wonderful neighborhood band"],
    ["{name} starts collecting interesting rocks and minerals", "Each rock tells a story of Earth's history", "A geological {animal} explains how rocks form", "Some rocks are millions of years old", "They traveled far distances to reach this place", "The {animal} teaches about different rock types", "{name} learns to identify various mineral characteristics", "Collecting becomes a scientific adventure and hobby", "Friends join {name} on rock hunting expeditions", "The collection becomes a learning museum for everyone"],
    ["{name} volunteers at the local animal shelter", "Many pets need love and temporary homes", "A caring {animal} shows {name} proper pet care", "Each animal has its own personality and needs", "Some are playful, others are quiet and gentle", "The {animal} teaches about responsible pet ownership", "{name} helps feed and exercise the shelter animals", "Finding good homes becomes {name}'s important mission", "Many pets find loving families through {name}'s help", "Caring for animals teaches compassion and responsibility"],
    ["{name} creates art using recycled materials only", "Plastic bottles become beautiful flower sculptures today", "An artistic {animal} shares creative recycling ideas", "Cardboard transforms into amazing castle structures easily", "Old magazines become colorful collage masterpieces quickly", "The {animal} explains how art helps the environment", "Creating reduces waste while making beauty simultaneously", "Friends learn to see trash as art supplies", "{name}'s recycled art inspires the whole neighborhood", "Art and environmental care work together perfectly"],
    ["{name} learns about different cultures through cooking", "Each recipe tells stories of faraway places", "A culinary {animal} shares traditional cooking wisdom", "Spices carry the flavors of different countries", "Cooking connects {name} to people around the world", "The {animal} explains cultural significance of various foods", "Sharing meals brings people together across all differences", "Food becomes a language everyone can understand", "{name} hosts international dinner parties for friends", "Cooking teaches respect for all world cultures"],
    ["{name} starts a weather observation science project", "Daily measurements track patterns in local climate", "A meteorological {animal} explains weather prediction methods", "Clouds tell stories about what weather approaches", "Temperature and humidity create different atmospheric conditions", "The {animal} teaches how weather affects all living things", "{name} learns to read nature's weather signs", "Accurate predictions help people plan their daily activities", "The project becomes valuable to the whole community", "Science helps everyone understand the natural world better"],
    ["{name} organizes neighborhood cleanup and beautification days", "Everyone works together improving their shared spaces", "An environmental {animal} teaches proper waste sorting", "Recycling and composting reduce harmful environmental impact", "Planting native flowers attracts helpful butterflies and bees", "The {animal} explains ecosystem connections and balances", "Clean neighborhoods make everyone feel proud and happy", "Working together builds strong community relationships naturally", "{name} sees how small actions create big positive changes", "Environmental stewardship becomes everyone's shared responsibility"],
    ["{name} learns basic first aid and safety skills", "A medical {animal} teaches proper emergency response techniques", "Knowing how to help others builds confidence", "Basic bandaging and cleaning cuts prevents infections", "The {animal} emphasizes staying calm during emergencies", "Safety knowledge helps protect family and friends", "{name} practices responding to different emergency scenarios", "Being prepared reduces fear and increases helpfulness", "These skills make {name} a valuable community member", "Knowledge and preparation save lives and prevent injuries"],
    ["{name} starts a pen pal exchange program", "Letters connect children from different countries worldwide", "A postal {animal} explains international mail systems", "Each letter shares cultural traditions and daily life", "Writing improves communication skills and cultural awareness", "The {animal} helps translate difficult words and phrases", "Friendships develop across continents through regular correspondence", "Different perspectives broaden {name}'s understanding of the world", "The program grows to include many schools", "Written communication builds lasting international friendships"],
    ["{name} creates a neighborhood newsletter for everyone", "Important community news keeps neighbors informed and connected", "A journalistic {animal} teaches proper news writing techniques", "Interviews with neighbors reveal interesting life stories", "The newsletter celebrates community achievements and upcoming events", "The {animal} explains the importance of accurate reporting", "Distribution brings neighbors together through shared information", "Local news strengthens community bonds and participation", "{name} becomes the voice of the neighborhood", "Communication builds stronger and more connected communities"],
    ["{name} learns astronomy and stargazing techniques carefully", "Night skies reveal ancient stories and scientific wonders", "An astronomical {animal} identifies constellations and their meanings", "Telescopes bring distant planets and stars closer", "Each celestial object has fascinating scientific properties", "The {animal} explains how space exploration advances human knowledge", "Star charts help navigate the complex night sky", "Astronomy connects {name} to the vastness of universe", "Friends join stargazing parties on clear nights", "Science reveals the beauty and mystery of cosmos"]
  ],

  hard: [
    // Original templates (1-3) maintained for consistency
    ["{name} lived peacefully in the beautiful {setting} with many friends", "One day something very strange and mysterious happened there", "The {animal}s started acting differently and seemed quite scared", "{name} noticed their fear and decided to help them", "{pronoun} bravely decided to investigate this very puzzling mystery", "With great courage {name} ventured into the unknown territory", "There {pronoun} discovered some {antagonist} creatures causing trouble everywhere", "{name} had to make a very difficult and important choice", "Using special {skill} abilities {name} found the perfect solution", "The {setting} became peaceful again and {name} grew much wiser"],
    ["{name} discovered an ancient clock hidden in the library", "When the hands moved backward, something incredible happened immediately", "The world around {name} began to shimmer and change colors", "{pronoun} found themselves in a completely different time period", "A helpful {animal} from that era explained the rules", "To return home, {name} must solve an important historical problem", "Working with people from the past proved challenging but rewarding", "{name} learned that every generation faces similar difficulties and joys", "By helping others, {pronoun} gained the power to return", "Back home, {name} treasured the wisdom gained from the journey"],
    ["{name} found a magical conch shell on the beach", "When blown, it opened a path beneath the ocean waves", "Swimming down, {pronoun} discovered an amazing underwater kingdom filled with life", "The sea creatures welcomed {name} as a special visitor", "A wise {animal} explained that their kingdom needed help", "Pollution from above was threatening their beautiful coral homes", "{name} promised to help protect the ocean and its creatures", "Together they devised a plan to clean the waters", "Through teamwork and determination, they succeeded in saving the kingdom", "{name} returned home as an ocean guardian and protector"],

    // NEW Enhanced Templates (4-15) - 7-13 words per page, complete thoughts
    ["{name} inherited a mysterious old house from a great-aunt", "Hidden rooms contained scientific equipment from a bygone era", "A scholarly {animal} explained the equipment's purpose and historical significance", "The great-aunt had been a secret inventor of helpful devices", "Each invention was designed to solve important community problems", "The {animal} taught {name} how to operate these amazing machines", "Together they discovered blueprints for even more beneficial inventions", "The basement laboratory held experiments that could change the world", "{name} decided to continue the great-aunt's important scientific work", "Innovation and scientific discovery became {name}'s passionate life mission"],
    ["{name} discovered a hidden talent for understanding animal languages completely", "Every creature from insects to elephants could communicate complex ideas", "A linguistic {animal} explained this rare gift's responsibilities and importance", "With great power comes the obligation to help solve conflicts", "Different species had been misunderstanding each other for centuries", "The {animal} guided {name} through the complexities of inter-species diplomacy", "Negotiations between predators and prey required delicate and sensitive mediation", "Environmental conflicts could be resolved through proper animal communication", "{name} became an ambassador between the human and animal worlds", "This unique ability fostered unprecedented cooperation between all living creatures"],
    ["{name} found an ancient seed that had been dormant for centuries", "When planted with special care, it grew into something extraordinary", "A botanical {animal} recognized the plant as extremely rare and valuable", "This species could purify polluted air and contaminated water sources", "The plant's unique properties offered solutions to environmental problems worldwide", "The {animal} taught {name} about proper cultivation and propagation techniques", "Careful breeding programs could produce enough plants to heal ecosystems", "Scientists from around the world wanted to study this remarkable discovery", "{name} became responsible for preserving and distributing this environmental miracle", "One small seed grew into hope for the planet's future"],
    ["{name} received an invitation to join a secret society of young inventors", "The organization had been operating quietly for over two hundred years", "A mechanical {animal} introduced {name} to the society's noble mission", "Members worked together creating inventions that helped solve global problems", "Each invention had to pass strict ethical and environmental review standards", "The {animal} mentored {name} through the challenging initiation process successfully", "Advanced workshops taught engineering principles far beyond typical school curricula", "Collaboration with brilliant minds from diverse backgrounds accelerated learning exponentially", "{name} contributed unique perspectives that enhanced the group's innovative capabilities", "The society's work secretly improved life for people everywhere"],
    ["{name} discovered that dreams could be shared and explored together", "A sleeping {animal} taught {name} the ancient art of dream navigation", "Shared dreaming allowed people to collaborate on solving complex problems", "Nightmares could be transformed into positive learning experiences through proper guidance", "The {animal} explained how dreams connect all sleeping minds across distances", "Careful practice enabled {name} to help others overcome their deepest fears", "Dream sharing created unprecedented levels of empathy and understanding between people", "Therapeutic applications helped heal trauma and promote emotional wellness naturally", "{name} established a network of dream guides to help others", "Sleep became a powerful tool for healing and human connection"],
    ["{name} found a time capsule containing messages from future generations", "The messages warned about critical decisions that needed to be made", "A prophetic {animal} helped {name} understand the timeline's complex implications", "Future people faced challenges that current actions could either solve or worsen", "Environmental and social choices made today would determine humanity's fate", "The {animal} guided {name} through the responsibility of possessing future knowledge", "Changing the present required careful consideration of all possible consequences", "Building coalitions became essential for implementing necessary positive changes gradually", "{name} became a bridge between present choices and future outcomes", "Responsibility for the future motivated {name} to become a dedicated environmental activist"],
    ["{name} inherited the ability to see the true emotional state of others", "This empathic gift revealed the hidden struggles people carried daily", "A compassionate {animal} taught {name} how to help without overwhelming others", "Understanding true emotions required learning when to offer help appropriately", "Some people needed space, others craved connection and understanding deeply", "The {animal} emphasized the importance of respecting personal boundaries while helping", "Emotional intelligence became {name}'s most powerful tool for building genuine relationships", "Creating safe spaces allowed others to heal from past hurts", "{name} established support networks that strengthened the entire community's emotional health", "True understanding of others' feelings fostered unprecedented levels of community compassion"],
    ["{name} discovered a portal to a dimension where music creates reality", "Every sound, rhythm, and melody shaped the physical world directly", "A musical {animal} explained the fundamental laws governing this harmonic universe", "Careful composition could heal sickness, grow food, and create shelter", "Discordant music caused chaos, while harmony brought peace and prosperity", "The {animal} taught {name} the responsibility that comes with creative power", "Musical collaboration between dimensions could solve problems in both worlds", "Learning to compose with intention required years of dedicated practice", "{name} became a conductor orchestrating positive change through musical creation", "Art and music proved to be the most powerful forces for transformation"],
    ["{name} found ancient scrolls describing a lost civilization's sustainable technologies", "These advanced techniques used only renewable resources and natural processes", "An archaeological {animal} helped decipher the complex technical diagrams and instructions", "The civilization had achieved perfect harmony between technology and natural ecosystems", "Their innovations could solve modern problems without creating new environmental damage", "The {animal} guided {name} through reconstructing these forgotten technological marvels", "Testing the ancient methods required careful experimentation and modern scientific validation", "Successful implementation could revolutionize how humanity interacts with the natural world", "{name} dedicated their life to reviving and adapting these sustainable technologies", "Ancient wisdom combined with modern knowledge created solutions for the future"],
    ["{name} received the ability to heal damaged ecosystems through focused intention", "Polluted rivers, barren lands, and poisoned air responded to {name}'s concentrated efforts", "An ecological {animal} taught the principles governing this environmental healing gift", "Restoration required understanding the complex relationships between all living systems", "Each ecosystem had unique needs that demanded specialized knowledge and approaches", "The {animal} emphasized that healing required patience, persistence, and deep ecological understanding", "Successful restoration projects attracted attention from environmental scientists and government officials", "Training others to develop similar abilities multiplied the positive environmental impact exponentially", "{name} established a global network of ecosystem healers working together", "Environmental restoration became humanity's most important collaborative effort for planetary survival"],
    ["{name} discovered the ability to see the life force energy in all living things", "This energy appeared as beautiful, colored light surrounding every creature and plant", "An energy-sensitive {animal} explained how to interpret these vital force patterns", "Healthy organisms glowed brightly, while sick ones showed dimmer, disrupted energy fields", "Learning to direct and balance life force energy enabled {name} to promote healing", "The {animal} taught the ethical responsibilities of working with life energy safely", "Healing animals, plants, and eventually people became {name}'s sacred calling", "Energy work required years of training to develop precision and avoid causing harm", "{name} established a healing center that integrated energy work with traditional medicine", "This holistic approach to health and wellness revolutionized medical treatment methods"],
    ["{name} found a device that could translate thoughts into multiple languages instantly", "This invention could eliminate communication barriers between all cultures and peoples", "A polyglot {animal} explained the profound implications of universal communication capability", "Misunderstandings between nations often stemmed from inadequate translation and cultural interpretation", "Perfect communication could prevent conflicts and foster unprecedented international cooperation", "The {animal} helped {name} understand the responsibility of possessing such powerful technology", "Careful implementation required consideration of cultural sensitivities and potential misuse", "International diplomacy could be revolutionized through perfect cross-cultural communication", "{name} became an ambassador promoting global understanding through improved communication", "Language barriers dissolved as humanity learned to truly understand each other"]
  ],

  expert: [
    // Original templates (1-3) maintained for consistency
    ["{name} began exploring the fascinating world of science and discovery", "Complex questions about nature and the universe seemed increasingly interesting and important", "A mysterious wise {animal} appeared unexpectedly offering guidance through unknown realms", "Together they carefully explored ancient mysteries hidden within the natural world", "{name} faced an important choice between personal desires and helping others", "The long challenging journey gradually revealed amazing truths about friendship and courage", "Through deep thinking and reflection {name} finally found lasting inner peace", "This transformative character growth completely changed {pronoun_possessive} understanding of life's principles", "Essential principles of kindness and balance became crystal clear to {name}", "{name} achieved a deeper understanding of friendship and {pronoun_possessive} purpose in life"],
    ["{name} encountered a series of profound questions that challenged conventional thinking", "Each question led to deeper contemplation about the nature of existence and meaning", "A enlightened {animal} served as both teacher and companion throughout this intellectual quest", "They explored concepts of justice, beauty, truth, and the interconnectedness of all things", "{name} gradually understood that wisdom comes not from having answers but asking questions", "The journey revealed that every person's perspective adds valuable insight to life's mysteries", "Through dialogue and reflection, {name} developed a more nuanced understanding of complex issues", "Personal growth emerged not from isolation but from meaningful connections with others", "The adventure culminated in {name} becoming a bridge between different ways of thinking", "Ultimately, {name} learned that the greatest discoveries come from embracing both questions and uncertainty"],
    ["{name} received an invitation to explore the vast mysteries of space and time", "Traveling beyond Earth's atmosphere revealed the incredible complexity and beauty of the cosmos", "An ancient {animal} being shared knowledge about civilizations that existed across the galaxy", "Each planet visited offered unique lessons about adaptation, cooperation, and sustainable living", "{name} discovered that intelligence takes countless forms throughout the universe's endless expanse", "The greatest challenge was learning to communicate across vastly different forms of consciousness", "Through patience and empathy, {name} built bridges between species that had never communicated", "These intergalactic relationships revealed universal principles of respect, curiosity, and mutual aid", "The journey transformed {name} into an ambassador for Earth and an advocate for cosmic cooperation", "Returning home, {name} carried the responsibility of sharing these profound lessons with humanity"],

    // NEW Enhanced Templates (4-12) - 9-16 words per page, complex thoughts
    ["{name} inherited responsibility for maintaining the delicate balance between parallel dimensions of reality", "Each dimension operated according to slightly different physical laws and moral principles governing existence", "A interdimensional {animal} guardian explained the complex consequences of actions across multiple realities simultaneously", "Decisions made in one dimension created ripple effects that influenced outcomes in all other parallel universes", "The responsibility required {name} to consider the welfare of infinite versions of every person", "Moral choices became exponentially more complex when considering their multidimensional implications and consequences", "The {animal} taught {name} to perceive the interconnected web of causality spanning across dimensional boundaries", "Balancing competing needs across dimensions demanded unprecedented levels of wisdom, compassion, and strategic thinking", "Every action required careful analysis of its potential impact on the stability of reality itself", "{name} became the guardian of multidimensional harmony, ensuring the continued existence of all possible worlds"],
    ["{name} discovered the ability to experience the collective memory of all humanity throughout history", "Every joy, sorrow, triumph, and tragedy ever experienced became accessible through concentrated meditation and reflection", "A transcendent {animal} guide helped {name} navigate the overwhelming flood of human emotional and intellectual experience", "Understanding the full scope of human suffering and achievement provided profound perspective on current challenges", "Historical patterns revealed the cyclical nature of human progress, regression, and the potential for transformation", "The {animal} taught {name} how to synthesize millennia of human wisdom into practical solutions", "Experiencing collective human memory fostered an unprecedented level of empathy and understanding for all people", "This knowledge carried the responsibility to help humanity learn from past mistakes and build better futures", "{name} became a bridge between the accumulated wisdom of the past and the potential of the future", "Through understanding the full spectrum of human experience, {name} developed solutions that honored both tradition and innovation"],
    ["{name} received the ability to perceive the fundamental mathematical patterns underlying all natural phenomena", "Every leaf, cloud, animal movement, and planetary orbit followed precise mathematical relationships and equations", "A mathematical {animal} consciousness explained how understanding these patterns could unlock the secrets of universal harmony", "Mathematics revealed the hidden order beneath apparent chaos in weather, ecosystems, and human behavior patterns", "Recognizing these patterns enabled {name} to predict and influence natural events for the benefit of all life", "The {animal} emphasized that this knowledge came with the responsibility to use it ethically and wisely", "Mathematical insights revealed how human activities could either harmonize with or disrupt natural patterns catastrophically", "Applying mathematical understanding to social problems revealed solutions to inequality, conflict, and environmental destruction", "{name} developed technologies that worked in perfect harmony with mathematical laws governing natural systems", "Understanding the mathematical nature of reality enabled {name} to help humanity live in balance with universal order"],
    ["{name} gained access to a cosmic library containing the accumulated knowledge of all intelligent civilizations", "This vast repository held solutions to every problem that sentient beings had ever encountered throughout the universe", "A librarian {animal} entity explained the protocols for accessing and applying this infinite knowledge responsibly", "Each piece of information came with detailed context about its proper application and potential consequences", "The knowledge included not only solutions but also warnings about technologies that had destroyed civilizations", "The {animal} taught {name} the crucial skill of determining which knowledge was appropriate for humanity's current development", "Premature access to advanced knowledge could cause more harm than benefit if not properly integrated", "Careful study revealed principles for guiding civilizations through technological and social advancement safely", "{name} became humanity's wise curator of cosmic knowledge, sharing insights that promoted sustainable progress", "The cosmic library became a tool for ensuring that humanity's advancement followed paths of wisdom rather than destruction"],
    ["{name} developed the ability to heal not just individuals but entire cultures from historical trauma", "Generational wounds passed down through families and communities required healing at the collective level", "A healing {animal} spirit guide taught {name} the techniques for addressing systemic and cultural pain", "Historical injustices created psychological patterns that continued to cause suffering across multiple generations", "Healing cultural trauma required understanding the complex interplay between individual and collective psychological processes", "The {animal} emphasized that true healing must address root causes rather than merely treating symptoms", "Cultural healing work required collaboration with affected communities and respect for their autonomous healing processes", "Successful healing transformed not only the traumatized groups but also the broader society's capacity for justice", "{name} established international protocols for cultural healing that became models for conflict resolution worldwide", "This work demonstrated that societies could heal from historical injustices and create more just and compassionate futures"],
    ["{name} received the responsibility for maintaining the planet's spiritual ecosystem alongside its physical environment", "Spiritual pollution from hatred, greed, and fear threatened the earth's energetic balance just as physical pollution threatened ecosystems", "A spiritually sensitive {animal} taught {name} to perceive and work with the planet's spiritual health", "Areas of intense conflict, injustice, or despair created spiritual toxic zones that affected all nearby life", "Healing these spiritual wounds required addressing their underlying causes in human consciousness and social systems", "The {animal} guided {name} in developing practices that could cleanse spiritual pollution and restore energetic balance", "Spiritual ecology work revealed the intimate connection between human consciousness and environmental health", "Communities practicing spiritual ecology experienced increased harmony, creativity, and sustainable prosperity", "{name} established a global network of spiritual ecologists working to heal the planet's energetic systems", "This work demonstrated that environmental healing required attention to both physical and spiritual dimensions of reality"],
    ["{name} inherited the ability to facilitate communication between the living and future generations yet unborn", "Future humans could share their perspectives on current decisions and their long-term consequences", "A temporal {animal} mediator helped {name} establish protocols for these cross-temporal conversations", "Future generations provided warnings about current practices that would create suffering for their descendants", "They also shared innovations and solutions that could be implemented in the present to ensure positive outcomes", "The {animal} taught {name} to balance present needs with future welfare in these complex negotiations", "Cross-temporal communication revealed the true cost of short-term thinking and the value of long-term planning", "Future perspectives helped current leaders make decisions that considered seven generations of consequences", "{name} became an advocate for future generations, ensuring their voices were heard in present-day decisions", "This communication bridge transformed human decision-making processes to consider the welfare of all future generations"],
    ["{name} gained the ability to see the life purpose and potential of every person they encountered", "This vision revealed the unique gifts that each individual could contribute to humanity's collective flourishing", "A visionary {animal} guide taught {name} how to help others recognize and develop their highest potential", "Many people had lost connection with their life purpose due to societal pressures and personal trauma", "Helping individuals reconnect with their purpose created ripple effects that transformed entire communities", "The {animal} emphasized that true leadership meant helping others become their most authentic and capable selves", "Purpose recognition work required deep listening skills and the ability to see beyond current limitations", "Creating environments where people could discover and express their purposes became {name}'s primary focus", "{name} established educational and community systems designed to nurture human potential rather than conform to standard expectations", "This work revealed that human flourishing required honoring the unique gifts and purposes of every individual"],
    ["{name} developed the capacity to perceive and work with the intelligence inherent in all natural systems", "Forests, rivers, mountains, and ecosystems possessed their own forms of consciousness and wisdom", "An ecological {animal} consciousness taught {name} to communicate with and learn from natural intelligence", "Natural systems had developed sustainable solutions to complex problems over millions of years of evolution", "Learning from natural intelligence provided blueprints for human technologies that worked in harmony with ecological principles", "The {animal} emphasized that humans were meant to be conscious participants in natural intelligence rather than separate from it", "Biomimicry guided by actual communication with natural systems produced revolutionary sustainable technologies", "Collaboration between human and natural intelligence created solutions that benefited both civilization and the environment", "{name} became a translator between human and natural intelligence, facilitating unprecedented cooperation", "This work demonstrated that the greatest innovations came from humble collaboration with nature's inherent wisdom"]
  ]
};

// PREMIUM TIER - Ultra-Robust System (40+ Easy, 35+ Medium, 25+ Hard, 20+ Expert)
const PREMIUM_TIER_TEMPLATES = {
  easy: [
    // Includes all free tier templates plus 15+ premium-exclusive templates
    ...FREE_TIER_TEMPLATES.easy,
    
    // Premium-exclusive templates with enhanced variety
    ["{name} meets a magic {animal}", "It can grant wishes", "But wishes help others", "{name} thinks hard", "Wish for {animal} friends", "To have enough {food}", "The magic works", "Everyone feels happy", "Good wishes come true", "Help others first"],
    ["{name} finds a rainbow bridge", "It leads to cloud land", "Soft fluffy white clouds", "A {animal} lives there", "It teaches about weather", "Rain helps flowers grow", "Sun gives warm light", "{name} learns nature", "Weather helps all life", "Nature works together"],
    ["{name} becomes very small", "Like an ant or bee", "A tiny {animal} helps", "They explore the garden", "See flowers up close", "Smell the sweet scents", "Learn about small creatures", "They do big important work", "{name} grows big again", "Small things matter too"],
    ["{name} travels through time", "To when {animal}s ruled", "Long long ago", "Dinosaurs everywhere", "Some big some small", "A friendly {animal} guides", "Shows how life changed", "Evolution teaches us", "{name} comes back home", "History helps us learn"],
    ["{name} learns to fly", "Like birds in the sky", "A flying {animal} teaches", "Start with small jumps", "Then bigger and bigger", "Feel the wind lift up", "See the world below", "Flying feels so free", "{name} lands softly", "Dreams can come true"],
    ["{name} speaks all languages", "Every {animal} understands", "From all around world", "Each has different sounds", "But feelings are same", "Love sounds like love", "Happy sounds like happy", "Words connect everyone", "{name} makes many friends", "Understanding brings peace"],
    ["{name} becomes invisible", "To help without being seen", "A sneaky {animal} explains", "Help must be kind", "Not for playing tricks", "Fix things quietly", "Make others smile", "Being good feels better", "{name} becomes visible again", "Kindness doesn't need praise"],
    ["{name} can talk to plants", "Flowers tell their stories", "A garden {animal} translates", "Plants need love too", "Water and sunshine", "Good soil to grow", "They clean the air", "Make oxygen for us", "{name} becomes plant friend", "Plants and people help each other"],
    ["{name} visits the moon", "In a rocket ship", "A space {animal} comes too", "Earth looks small below", "Blue and green and pretty", "The moon has no air", "Stars shine so bright", "Space is big and quiet", "{name} returns to Earth", "Our planet is special"],
    ["{name} becomes a superhero", "With power to heal", "A brave {animal} partners", "They help hurt animals", "Heal broken wings", "Mend scraped knees", "Make sadness go away", "Healing is real superpower", "{name} helps everyone", "Love heals all wounds"],
    ["{name} opens a magic door", "To a candy land", "A sweet {animal} lives there", "Everything tastes good", "But too much sugar", "Makes tummies hurt", "The {animal} teaches balance", "Some sweet some healthy", "{name} learns moderation", "Good choices feel better"],
    ["{name} becomes a teacher", "For baby {animal}s", "A wise old {animal} helps", "Teaching requires patience", "Show don't just tell", "Let them try and learn", "Mistakes help us grow", "Every student is different", "{name} loves teaching", "Learning never stops"],
    ["{name} can freeze time", "To help in emergencies", "A quick {animal} explains", "Stop bad things happening", "Give people more time", "To make good choices", "Time is very precious", "Use it to help others", "{name} unfreezes time", "Every moment matters"],
    ["{name} becomes a detective", "Solving animal mysteries", "A clever {animal} assists", "Look for clues everywhere", "Listen to all sides", "Think before deciding", "Truth is important", "Justice helps everyone", "{name} solves the case", "Fair solutions work best"],
    ["{name} learns to sing magic", "Songs that heal hearts", "A musical {animal} teaches", "Different songs for different feelings", "Sad songs help crying", "Happy songs bring joy", "Lullabies help sleep", "Music speaks to souls", "{name} sings for others", "Music heals the world"]
  ],

  medium: FREE_TIER_TEMPLATES.medium, // Premium gets same base + AI-generated variations

  hard: FREE_TIER_TEMPLATES.hard, // Premium gets same base + AI-generated variations  

  expert: FREE_TIER_TEMPLATES.expert // Premium gets same base + AI-generated variations
};

export const ROBUST_STORY_TEMPLATES: TemplateSystem = {
  free: FREE_TIER_TEMPLATES,
  premium: PREMIUM_TIER_TEMPLATES
};

// Template selection with tier-specific intelligence
export const getRobustTemplate = (
  difficulty: string, 
  tier: 'free' | 'premium', 
  templateIndex?: number,
  excludeRecent?: number[]
): string[] => {
  const templates = ROBUST_STORY_TEMPLATES[tier][difficulty as keyof typeof ROBUST_STORY_TEMPLATES.free] || ROBUST_STORY_TEMPLATES.free.easy;
  
  let availableTemplates = [...templates];
  
  // Filter out recently used templates for better variety
  if (excludeRecent && excludeRecent.length > 0) {
    availableTemplates = templates.filter((_, index) => !excludeRecent.includes(index));
  }
  
  // If all templates are excluded, reset and use all templates
  if (availableTemplates.length === 0) {
    availableTemplates = [...templates];
  }
  
  if (templateIndex !== undefined && templateIndex < availableTemplates.length) {
    return availableTemplates[templateIndex];
  }
  
  return availableTemplates[Math.floor(Math.random() * availableTemplates.length)];
};

// Get template pool stats for debugging/analytics
export const getTemplatePoolStats = (tier: 'free' | 'premium') => {
  const templates = ROBUST_STORY_TEMPLATES[tier];
  return {
    tier,
    easy: templates.easy.length,
    medium: templates.medium.length,
    hard: templates.hard.length,
    expert: templates.expert.length,
    total: templates.easy.length + templates.medium.length + templates.hard.length + templates.expert.length
  };
};