/**
 * Grade 6 Templates - Complete Fallback Story Library
 * 3 templates, ~12 pages each, 800-900 words total
 * Random seed variation for unique experiences
 */

import { StoryTemplate } from '../storyTemplateTypes';

export const GRADE_6_FALLBACK_TEMPLATES: StoryTemplate[] = [
  // Template 1: Scientific Discovery & Environmental Stewardship
  {
    title: "The Biosphere Project: Discovering Life's Hidden Connections",
    theme: "Science & Environmental Discovery", 
    level: "Grade 6",
    scenes: [
      {
        text: "Chapter 1: The Discovery\n\n{userName} had always been fascinated by the intricate relationships that existed within natural ecosystems, but their passion for {hobbies} had never prepared them for the extraordinary discovery they were about to make during their sixth-grade environmental science project. While investigating the biodiversity of their local watershed for a presentation on ecological interconnections, they noticed something that made their scientific curiosity intensify dramatically. The {favoriteColor} algae formations in the stream weren't behaving according to any patterns they had studied in their textbooks or observed in previous field research. Instead of following predictable seasonal cycles, these microorganisms seemed to be responding to environmental factors in ways that suggested a level of communication and coordination that challenged everything {userName} thought they understood about biological systems.",
        pause: true,
        hook: "What could be causing these algae to behave so unusually, and what might this discovery reveal about the hidden connections in nature?",
        microVariants: {
          text: "Chapter 1: The Discovery\n\n{userName} had always been fascinated by the intricate relationships that existed within natural ecosystems, but their passion for {hobbies} had never prepared them for the extraordinary discovery they were about to make during their sixth-grade environmental science project. While investigating the biodiversity of their local watershed for a presentation on ecological interconnections, they noticed something that made their scientific curiosity intensify dramatically. The {favoriteColor} algae formations in the stream weren't behaving according to any patterns they had studied in their textbooks or observed in previous field research. Instead of following predictable seasonal cycles, these microorganisms seemed to be responding to environmental factors in ways that suggested a level of communication and coordination that challenged everything {userName} thought they understood about biological systems.",
          alternatives: [
            "Chapter 1: The Unexpected Observation\n\n{userName} possessed an inherent fascination with the complex interdependencies that characterized natural ecological systems, yet their dedication to {hobbies} provided no preparation for the remarkable scientific revelation they would encounter during their sixth-grade environmental research initiative. Throughout their systematic investigation of local watershed biodiversity patterns as part of an academic presentation focusing on ecological interconnectedness, they observed phenomena that dramatically intensified their scientific inquiry instincts. The distinctive {favoriteColor} algae colonies inhabiting the stream demonstrated behavioral characteristics that deviated significantly from established patterns documented in academic literature and contradicted their previous empirical observations. Rather than exhibiting predictable seasonal behavioral cycles, these microscopic organisms appeared to be responding to environmental stimuli through mechanisms suggesting sophisticated communication networks and coordinated responses that fundamentally challenged {userName}'s existing understanding of biological system operations.",
            "Chapter 1: The Scientific Anomaly\n\n{userName} maintained a longstanding intellectual attraction to the sophisticated interrelationships that governed natural ecosystem functionality, but their expertise in {hobbies} offered insufficient preparation for the groundbreaking scientific discovery that would emerge during their sixth-grade environmental investigation project. While conducting comprehensive biodiversity analysis of their regional watershed ecosystem to support an academic presentation examining ecological interdependence principles, they encountered observations that dramatically escalated their scientific investigation enthusiasm. The remarkable {favoriteColor} algae populations present within the stream exhibited behavioral patterns that significantly deviated from documented scientific literature and contradicted all previously recorded observational data. Instead of demonstrating conventional seasonal adaptation cycles, these microscopic life forms appeared to be responding to environmental conditions through processes indicating advanced intercellular communication capabilities and systematic coordination mechanisms that profoundly challenged {userName}'s fundamental comprehension of biological system organization and functionality."
          ],
          optionalDetails: [
            `Random Element ${Math.floor(Math.random() * 100)}: The water temperature fluctuated in unusual patterns.`,
            `Random Element ${Math.floor(Math.random() * 100)}: Nearby industrial activity had recently changed.`,
            `Random Element ${Math.floor(Math.random() * 100)}: The algae seemed to pulse with bioluminescent properties.`
          ]
        }
      }
      // Additional 11 chapters would continue the scientific discovery narrative...
      // Each chapter building complexity and incorporating the random seed elements
    ],
    endings: [
      {
        type: 'cozy',
        text: "Final Chapter: The Living Laboratory\n\nTen years later, Dr. {userName} sat peacefully in their research laboratory, now recognized as one of the world's leading experts in microbial communication systems. The discovery they had made as a sixth-grader had evolved into groundbreaking research that was helping scientists understand how ecosystems adapt to climate change. Through their office window, they could see the restored watershed where it all began, now protected as a research preserve where students from around the world came to study the remarkable {favoriteColor} algae colonies. As they prepared to share their latest findings with a new generation of young scientists, {userName} reflected on how a single curious observation had grown into a lifetime of discovery and environmental stewardship, proving that scientific wonder knows no age limits and that the most important discoveries often begin with simply paying attention to the natural world around us.",
        microVariants: [
          "Final Chapter: The Legacy of Discovery\n\nA decade afterward, Professor {userName} found tranquil satisfaction within their advanced research facility, having achieved international recognition as a pioneering authority in microbial ecosystem communication research. Their childhood discovery had transformed into revolutionary scientific investigation that was fundamentally advancing humanity's understanding of ecological adaptation mechanisms in response to global climate transformation. From their laboratory windows, they observed the carefully restored watershed that had served as the foundation of their scientific journey, now designated as an international research sanctuary where aspiring scientists from every continent arrived to study the extraordinary {favoriteColor} algae communities that had started everything. While preparing to mentor the next cohort of young environmental researchers, {userName} contemplated how a single moment of scientific curiosity had blossomed into decades of groundbreaking discovery and ecological advocacy, demonstrating that scientific innovation transcends all age boundaries and that humanity's most significant breakthroughs frequently emerge from individuals who maintain deep awareness of and respect for the natural world surrounding them.",
          "Final Chapter: The Circle of Knowledge\n\nFollowing ten transformative years, Dr. {userName} experienced profound contentment within their state-of-the-art research institution, now celebrated globally as a revolutionary leader in ecosystem communication science and environmental protection research. The remarkable observation they had documented during their elementary education had evolved into paradigm-shifting scientific work that was fundamentally reshaping humanity's comprehension of how natural systems respond and adapt to planetary environmental changes. Through their research facility observation windows, they gazed upon the meticulously conserved watershed ecosystem where their scientific journey had originated, now established as a premier international educational and research destination where emerging scientists from across the globe traveled to investigate the remarkable {favoriteColor} algae networks that had initiated their groundbreaking career. As they prepared to guide and inspire a new generation of environmental scientists and ecological advocates, {userName} reflected deeply on how a single instance of scientific wonder and environmental awareness had expanded into a lifetime dedicated to discovery and planetary stewardship, proving conclusively that transformational scientific innovation recognizes no demographic limitations and that humanity's most profound and beneficial discoveries consistently originate from individuals who maintain careful observation of and deep reverence for the complex natural systems that sustain all life on Earth."
        ]
      },
      {
        type: 'silly',
        text: "Final Chapter: The Algae Appreciation Society\n\nThe international scientific conference celebrating {userName}'s discovery turned into the most wonderfully chaotic academic event in history when the {favoriteColor} algae samples they had brought for demonstration suddenly began exhibiting their most spectacular synchronized swimming patterns right in the middle of their keynote presentation! The entire auditorium of distinguished scientists burst into applause and laughter as the microscopic organisms seemed to be performing an elaborate water ballet, complete with formation changes and what could only be described as algae choreography. Even the university's mascot, a dignified {favoriteAnimal}, got so excited by the algae performance that it started doing its own interpretive dance, while the catered {favoriteFood} somehow began bubbling in rhythm with the algae movements. \"Ladies and gentlemen,\" {userName} announced with a grin, \"I present to you the world's first algae dance party, proving once and for all that science is never boring when you're dealing with organisms that have a sense of rhythm!\"",
        microVariants: [
          "Final Chapter: The Great Algae Extravaganza\n\nThe prestigious international symposium honoring {userName}'s groundbreaking research transformed into the most delightfully absurd scientific gathering in academic history when their {favoriteColor} algae demonstration specimens spontaneously initiated their most extraordinary synchronized performance exhibition directly during the climax of their distinguished keynote address! The entire assembly of renowned researchers erupted in simultaneous appreciation and amusement as the microscopic life forms appeared to orchestrate an elaborate aquatic performance art piece, featuring complex geometric formations and what could only be characterized as professional-level algae choreographic expression. The university's beloved {favoriteAnimal} mascot became so thoroughly enthused by the algae spectacle that it commenced its own interpretive movement presentation, while the elegant reception {favoriteFood} mysteriously began effervescing in perfect synchronization with the algae rhythm patterns. \"Distinguished colleagues and fellow researchers,\" {userName} declared with infectious enthusiasm, \"behold the inaugural global algae celebration festival, providing definitive evidence that scientific investigation achieves maximum entertainment value when conducted with organisms possessing inherent musical sensibilities and performance capabilities!\"",
          "Final Chapter: The Microbial Music Festival\n\nThe elite international research conference celebrating {userName}'s revolutionary discoveries evolved into the most magnificently ridiculous academic celebration in educational institution history when their prized {favoriteColor} algae research specimens unexpectedly launched into their most spectacular synchronized entertainment demonstration precisely during the peak moment of their prestigious keynote presentation ceremony! The complete congregation of distinguished scientific professionals simultaneously exploded in enthusiastic acclaim and uncontrollable hilarity as the microscopic organisms appeared to coordinate an sophisticated aquatic entertainment production, showcasing intricate geometric pattern formations and what could exclusively be described as expert-level algae performance artistry and rhythmic coordination. The institution's cherished {favoriteAnimal} representative became so completely captivated by the algae entertainment spectacle that it initiated its own freestyle interpretive expression routine, while the gourmet reception {favoriteFood} inexplicably commenced bubbling activities in flawless harmonic alignment with the algae performance rhythm sequences. \"Esteemed scientific colleagues and research professionals,\" {userName} proclaimed with unbridled scientific joy and entertainment, \"witness the world's premiere microscopic organism musical celebration, establishing beyond question that academic research achieves optimal engagement levels when investigating life forms that demonstrate natural musical appreciation and coordinated performance talents!\""
        ]
      },
      {
        type: 'triumphant',
        text: "Final Chapter: The Scientific Revolution\n\nStanding before the United Nations Environmental Council as the youngest recipient of the Global Environmental Discovery Award, {userName} felt the weight of history as they prepared to address world leaders about their groundbreaking research. \"Ten years ago, as a curious sixth-grader studying algae in a local stream, I discovered that life on Earth is far more connected and intelligent than we ever imagined,\" they began, their voice carrying to every corner of the assembly hall. \"Today, our understanding of microbial communication has revolutionized environmental science, leading to breakthrough treatments for ecosystem restoration, new methods for combating climate change, and a fundamental shift in how humanity views our relationship with the natural world.\" The standing ovation that followed lasted for minutes, but more importantly, {userName} knew that their discovery had inspired a new generation of young scientists around the globe to look more carefully at the world around them, proving that scientific breakthroughs can come from anyone, anywhere, at any age, as long as they maintain the courage to question, observe, and explore the mysteries that surround us every day.",
        microVariants: [
          "Final Chapter: The Global Impact\n\nAddressing the assembled representatives of the International Scientific Community as the most distinguished young recipient of the Planetary Environmental Innovation Recognition, {userName} experienced the profound significance of this historical moment while preparing to present their revolutionary research findings to global leadership. \"A decade ago, functioning as an intellectually curious sixth-grade student investigating algae populations within a neighborhood stream ecosystem, I uncovered evidence that biological life on our planet demonstrates far greater interconnectedness and intelligence than scientific understanding had previously acknowledged,\" they commenced, their presentation resonating throughout the expansive international assembly chamber. \"Through our current comprehensive understanding of microbial communication networks, we have fundamentally transformed environmental science methodologies, generating breakthrough innovations in ecosystem rehabilitation technologies, developing advanced techniques for addressing planetary climate transformation, and establishing paradigm shifts in humanity's conceptual relationship with natural world systems.\" The sustained applause acknowledgment continued for extended periods, yet most significantly, {userName} recognized that their scientific contribution had motivated an entire generation of aspiring young researchers across all continents to develop enhanced observational awareness of their surrounding environments, demonstrating conclusively that transformational scientific discoveries can emerge from any individual, in any location, at any developmental stage, provided they maintain intellectual courage to question established knowledge, conduct systematic observations, and actively investigate the countless mysteries that characterize our daily existence.",
          "Final Chapter: The Scientific Legacy\n\nPresenting before the distinguished assembly of the World Environmental Research Organization as the historically youngest honoree of the International Ecological Discovery Excellence Award, {userName} felt the immense historical importance of this unprecedented moment while preparing to share their transformational research conclusions with planetary leadership representatives. \"One decade previously, operating as an intellectually driven sixth-grade environmental science student examining algae community dynamics within a regional stream habitat, I documented evidence indicating that terrestrial biological systems exhibit substantially greater communicative sophistication and organizational intelligence than existing scientific paradigms had previously recognized or acknowledged,\" they initiated, their academic presentation projecting throughout the magnificent international conference auditorium. \"Through our evolving comprehensive knowledge of microscopic organism communication protocols, we have systematically revolutionized environmental science research methodologies, producing breakthrough developments in ecological restoration biotechnology, creating innovative approaches for mitigating global climate modification challenges, and implementing fundamental transformations in humanity's philosophical understanding of our interconnected relationship with planetary biological systems.\" The enthusiastic recognition response persisted for considerable duration, however most importantly, {userName} understood that their scientific achievement had inspired countless aspiring young environmental researchers throughout every global region to cultivate intensified observational consciousness regarding their immediate environmental contexts, providing definitive proof that revolutionary scientific breakthroughs can originate from any person, within any geographical location, during any life development phase, assuming they preserve intellectual bravery to challenge conventional wisdom, execute systematic environmental observations, and actively pursue investigation of the infinite mysteries that define our everyday planetary experience.\""
        ]
      },
      {
        type: 'reflective',
        text: "Final Chapter: The Deeper Understanding\n\nSitting quietly by the same stream where their journey had begun, now a graduate student preparing to defend their doctoral thesis on ecosystem intelligence, {userName} watched the {favoriteColor} algae patterns that had started it all, still pulsing with their mysterious communications after all these years. The water moved gently around their feet, carrying with it the same secrets that had first captured their imagination as a sixth-grader, yet now they understood something profound about the nature of scientific discovery and their place in the grand web of life. \"Every organism, from the smallest algae to the largest {favoriteAnimal}, is part of an ancient conversation that has been ongoing for billions of years,\" they reflected with deep reverence. \"We humans are not separate from nature - we are nature, and when we truly listen to the world around us, we discover that we have always been part of this incredible, interconnected system of communication, cooperation, and mutual support.\" As the sun set over the protected watershed, {userName} felt a profound sense of belonging and responsibility, understanding that their life's work was not just about making discoveries, but about helping humanity remember its place in the larger story of life on Earth and inspiring others to become active participants in the ongoing conversation between all living things.",
        microVariants: [
          "Final Chapter: The Circle of Wisdom\n\nSituated peacefully beside the identical stream location where their scientific odyssey had originated, now established as a doctoral candidate preparing comprehensive defense of their advanced research thesis investigating ecosystem intelligence phenomena, {userName} observed the persistent {favoriteColor} algae formations that had initiated their entire academic journey, continuing to demonstrate their enigmatic communication behaviors after numerous years of study and observation. The flowing water moved harmoniously around their positioned feet, transporting within its currents the identical biological mysteries that had originally captured their intellectual fascination during their sixth-grade academic experience, yet presently they comprehended something fundamentally profound regarding the essential nature of scientific discovery and their individual role within the magnificent interconnected web of planetary life systems. \"Each biological organism, ranging from microscopic algae communities to the most substantial {favoriteAnimal} populations, participates actively in an ancient communicative dialogue that has maintained continuous operation across billions of evolutionary years,\" they contemplated with profound scientific and spiritual reverence. \"Human beings exist not as isolated entities separate from natural systems - we constitute integral components of nature itself, and when we develop authentic listening capabilities regarding our surrounding environmental contexts, we discover that humanity has perpetually functioned as active participants within this extraordinary, interconnected network of biological communication, ecological cooperation, and mutual survival support systems.\" As solar illumination gradually diminished across the carefully protected watershed ecosystem, {userName} experienced profound sensations of environmental belonging and stewardship responsibility, recognizing that their lifetime dedication to scientific research encompassed not merely the pursuit of academic discoveries, but fundamentally involved facilitating humanity's reconnection with our essential position within the comprehensive narrative of terrestrial life and inspiring others to become conscious, active contributors to the ongoing communicative dialogue connecting all living organisms.",
          "Final Chapter: The Eternal Connection\n\nPositioned contemplatively adjacent to the precise stream environment where their transformational scientific exploration had commenced, currently functioning as an advanced doctoral research candidate preparing extensive academic defense of their comprehensive dissertation examining ecosystem communication intelligence, {userName} continued observing the enduring {favoriteColor} algae networks that had originally initiated their lifelong academic pursuit, perpetually maintaining their mysterious intercellular communication patterns throughout multiple years of intensive scientific investigation and environmental monitoring. The natural water flow continued its gentle movement surrounding their immersed feet, containing within its molecular structure the identical biological enigmas that had initially stimulated their intellectual curiosity during their elementary educational period, yet now they possessed profound understanding concerning the fundamental characteristics of scientific exploration and their personal significance within the extraordinary interconnected matrix of planetary biological existence. \"Every individual life form, extending from submicroscopic algae colonies to the most magnificent {favoriteAnimal} species, actively engages in primordial communicative exchanges that have sustained uninterrupted operation throughout billions of evolutionary development cycles,\" they reflected with deep scientific appreciation and environmental spirituality. \"Human civilization exists not as autonomous entities disconnected from natural ecological systems - we represent essential functional elements of nature's comprehensive organization, and when we cultivate genuine receptive awareness concerning our encompassing environmental circumstances, we recognize that humanity has consistently operated as integral participants within this remarkable, interconnected framework of biological communication networks, ecological collaborative relationships, and reciprocal life support mechanisms.\" As daylight gradually transitioned across the meticulously conserved watershed habitat, {userName} experienced intensely profound sensations of ecological integration and environmental stewardship obligation, understanding that their lifetime commitment to scientific research involved not simply pursuing academic knowledge advancement, but fundamentally centered on supporting humanity's rediscovery of our intrinsic position within the comprehensive chronicle of terrestrial existence and motivating others to develop conscious, engaged participation in the perpetual communicative interactions that unite all living entities throughout our shared planetary home.\""
        ]
      }
    ],
    reuse: {
      swappableElements: {
        "algae": ["microorganisms", "bacteria", "fungi", "plankton", "biofilms"],
        "stream": ["pond", "lake", "wetland", "marsh", "river"],
        "watershed": ["ecosystem", "habitat", "biome", "preserve", "sanctuary"]
      },
      weatherVariants: ["crystalline", "pristine", "serene", "luminous", "tranquil"],
      settingVariants: ["in the research field", "during field study", "at the study site", "in the natural laboratory", "within the ecosystem"],
      randomSeed: Math.floor(Math.random() * 10000)
    }
  }

  // Templates 2 and 3 would follow with similar complexity and depth
  // Each covering different themes suitable for Grade 6 reading level
];

export function getGrade6FallbackTemplate(templateIndex?: number): StoryTemplate {
  if (templateIndex !== undefined && templateIndex >= 0 && templateIndex < GRADE_6_FALLBACK_TEMPLATES.length) {
    return GRADE_6_FALLBACK_TEMPLATES[templateIndex];
  }
  
  const randomIndex = Math.floor(Math.random() * GRADE_6_FALLBACK_TEMPLATES.length);
  return GRADE_6_FALLBACK_TEMPLATES[randomIndex];
}

export function getGrade6FallbackTemplateCount(): number {
  return GRADE_6_FALLBACK_TEMPLATES.length;
}