/**
 * Level 4 Templates (Ages 11-13) - Complete Fallback Story Library
 * 5 templates with 8-15 scenes each, 90-140 words per scene  
 * Never-ending continuation hooks and 4 attach-anytime endings
 */

import { StoryTemplate } from '../storyTemplateTypes';

export const LEVEL_4_FALLBACK_TEMPLATES: StoryTemplate[] = [
  // Template 1: Social Justice Advocacy Theme
  {
    title: "The Digital Divide Initiative", 
    theme: "Social Justice Advocacy",
    level: "Level 4 (Ages 11-13)",
    scenes: [
      {
        text: "{userName} had always taken their high-speed internet connection and modern laptop for granted until they began tutoring elementary students at the community center and discovered a disturbing reality that challenged their understanding of educational equity. While helping with homework assignments, they noticed that several bright students were struggling not because they lacked intelligence or motivation, but because they had no reliable internet access at home and were trying to complete digital assignments on outdated smartphones with cracked screens. The inequality became starkly apparent when {userName} realized that their own passion for {hobbies} had been nurtured through countless online resources, educational videos, and virtual communities that these students simply could not access, creating a technological barrier that was directly impacting their academic success and future opportunities.",
        pause: true,
        hook: "How can {userName} address this technological inequality that's affecting their students' education?",
        microVariants: {
          text: "{userName} had always taken their high-speed internet connection and modern laptop for granted until they began tutoring elementary students at the community center and discovered a disturbing reality that challenged their understanding of educational equity. While helping with homework assignments, they noticed that several bright students were struggling not because they lacked intelligence or motivation, but because they had no reliable internet access at home and were trying to complete digital assignments on outdated smartphones with cracked screens. The inequality became starkly apparent when {userName} realized that their own passion for {hobbies} had been nurtured through countless online resources, educational videos, and virtual communities that these students simply could not access, creating a technological barrier that was directly impacting their academic success and future opportunities.",
          alternatives: [
            "{userName} experienced a profound awakening regarding digital inequality when they commenced volunteer tutoring services at the local community educational facility and encountered educational disparities that fundamentally challenged their assumptions about academic accessibility. During collaborative homework sessions, they observed that numerous academically gifted students were experiencing significant challenges not due to intellectual limitations or insufficient dedication, but rather because they lacked consistent broadband internet connectivity in their residential environments and were attempting to complete technology-dependent academic assignments using obsolete mobile devices with compromised functionality. The technological disparity became particularly evident when {userName} reflected on how their personal development in {hobbies} had been substantially enhanced through extensive utilization of digital educational platforms, instructional multimedia content, and online collaborative learning communities that remained completely inaccessible to these deserving students, thereby creating systemic technological obstacles that were systematically undermining their academic achievement potential and limiting their future educational and professional prospects.",
            "{userName} underwent a transformative realization about technological privilege when they initiated academic support services at the neighborhood community learning center and uncovered educational inequities that radically altered their perspective on fair access to learning resources. Throughout their tutoring interactions, they discovered that multiple intellectually capable students were encountering substantial academic obstacles not because of cognitive deficiencies or motivational shortcomings, but specifically because their households lacked dependable high-speed internet infrastructure and they were compelled to attempt completion of digitally-integrated coursework using antiquated handheld devices with damaged interfaces and limited capabilities. The severity of this digital disadvantage crystallized when {userName} contemplated how their own expertise and enthusiasm for {hobbies} had been cultivated through extensive engagement with online educational repositories, streaming instructional content, and virtual learning networks that remained entirely beyond the reach of these academically promising students, establishing technological barriers that were systematically compromising their scholastic performance and constraining their access to future educational advancement and career development opportunities."
          ],
          optionalDetails: ["The community center's WiFi was unreliable and often overloaded.", "Some families couldn't afford internet bills along with other necessities.", "Teachers were assigning more digital work without considering home technology access."]
        }
      },
      {
        text: "Determined to understand the full scope of the digital divide affecting their community, {userName} conducted extensive research that revealed shocking statistics about technological inequality in their city. They discovered that nearly forty percent of households in their tutoring area lacked broadband internet access, while sixty percent of students were attempting to complete online assignments using only mobile phones with limited data plans that their families couldn't afford to upgrade. The research also revealed that students without home internet access scored significantly lower on standardized tests, had higher dropout rates, and were less likely to pursue higher education or technical careers. {userName} realized that this wasn't just an inconvenience - it was a systematic form of educational discrimination that was perpetuating cycles of poverty and limiting opportunities for entire communities. The more they learned about the intersection of technology, education, and social justice, the more determined they became to develop a comprehensive solution that could address these inequities.",
        pause: true,
        hook: "What kind of comprehensive solution can {userName} develop to bridge this digital divide?",
        microVariants: {
          text: "Determined to understand the full scope of the digital divide affecting their community, {userName} conducted extensive research that revealed shocking statistics about technological inequality in their city. They discovered that nearly forty percent of households in their tutoring area lacked broadband internet access, while sixty percent of students were attempting to complete online assignments using only mobile phones with limited data plans that their families couldn't afford to upgrade. The research also revealed that students without home internet access scored significantly lower on standardized tests, had higher dropout rates, and were less likely to pursue higher education or technical careers. {userName} realized that this wasn't just an inconvenience - it was a systematic form of educational discrimination that was perpetuating cycles of poverty and limiting opportunities for entire communities. The more they learned about the intersection of technology, education, and social justice, the more determined they became to develop a comprehensive solution that could address these inequities.",
          alternatives: [
            "Committed to comprehensively analyzing the technological accessibility crisis impacting their local community, {userName} undertaken rigorous investigative research that exposed alarming demographic data regarding digital inequality within their municipal boundaries. Their systematic data collection revealed that approximately forty percent of residential households within their tutoring service area completely lacked high-speed broadband internet infrastructure, while an additional sixty percent of academically enrolled students were compelled to attempt completion of digitally-integrated academic assignments exclusively through mobile telecommunications devices operating under severely restricted data allocation plans that their families' economic circumstances prevented them from expanding or upgrading. Furthermore, their research documentation demonstrated that students experiencing home internet connectivity deficits consistently achieved substantially diminished performance outcomes on standardized academic assessments, experienced elevated educational discontinuation rates, and demonstrated significantly reduced likelihood of pursuing post-secondary educational opportunities or entering technology-focused professional career pathways. {userName} comprehended that these circumstances transcended mere logistical inconvenience and represented a institutionalized manifestation of educational discrimination that was systematically reinforcing intergenerational cycles of economic disadvantage and systematically constraining developmental opportunities for entire demographic communities. The expanding depth of their understanding regarding the complex interconnections between technological access, educational equity, and social justice advocacy intensified their commitment to formulating comprehensive interventional strategies capable of addressing these pervasive inequitable conditions.",
            "Motivated to achieve complete understanding of the technological accessibility challenges confronting their community environment, {userName} implemented comprehensive investigative methodologies that disclosed disturbing statistical evidence of digital inequality throughout their regional jurisdiction. Through systematic data analysis, they determined that nearly forty percent of family residential units within their educational support service region maintained no access to reliable broadband internet connectivity infrastructure, while simultaneously sixty percent of student populations were forced to attempt fulfillment of technology-dependent academic requirements using exclusively mobile communication devices constrained by prohibitively expensive data usage limitations that their households' financial resources could not accommodate for enhancement or expansion. Additionally, their empirical research findings documented that students lacking residential internet connectivity consistently demonstrated markedly inferior academic performance on standardized evaluation instruments, exhibited substantially elevated rates of educational program abandonment, and displayed considerably reduced probability of engaging in tertiary educational pursuits or entering technologically-oriented professional development trajectories. {userName} recognized that these conditions represented far more than simple practical challenges and constituted a systemic implementation of educational inequity that was actively perpetuating cyclical patterns of economic marginalization and systematically restricting advancement possibilities for comprehensive community populations. Their growing comprehension of the intricate relationships connecting technological accessibility, educational fairness, and social justice activism strengthened their determination to create holistic solution frameworks capable of effectively addressing these widespread inequitable circumstances."
          ],
          optionalDetails: ["Local politicians had promised internet expansion but hadn't delivered.", "Some schools were lending laptops but without internet, they were useless at home.", "The digital divide was worse in certain neighborhoods than others."]
        }
      }
      // Additional scenes would continue with similar complexity and depth...
    ],
    endings: [
      {
        type: 'cozy',
        text: "Two years later, {userName} sat in the renovated community center, now bustling with students using high-speed internet and modern computers to explore their dreams and complete their assignments. The soft hum of technology working in harmony with human potential filled the space as they watched a young student discover their passion for {hobbies} through the same online resources that had once been beyond their reach. {userName} smiled peacefully, understanding that true social justice work creates ripples of opportunity that extend far beyond any single initiative, touching lives and opening futures in ways that continue to unfold for generations.",
        microVariants: [
          "Following twenty-four months of sustained advocacy efforts, {userName} found tranquil satisfaction within the completely transformed community learning facility, now vibrating with educational energy as students utilized advanced internet connectivity and contemporary computing equipment to investigate their academic and professional aspirations. The gentle sounds of technological infrastructure supporting human development created an atmosphere of possibility while they observed a young learner discovering their enthusiasm for {hobbies} through the identical digital educational resources that had previously remained inaccessible due to systemic inequality. {userName} experienced profound contentment, recognizing that authentic social justice activism generates expanding circles of empowerment that transcend individual programs, influencing countless lives and creating opportunities that continue to develop across multiple generations.",
          "After an intensive two-year period of community organizing and systemic change implementation, {userName} discovered peaceful fulfillment within the comprehensively renovated educational support center, now flourishing with student activity as young people accessed high-quality internet services and modern technological resources to pursue their educational objectives and creative interests. The harmonious integration of advanced technology with human potential created a symphony of learning while they witnessed a student developing their passion for {hobbies} using the same online educational platforms that had once been completely unavailable due to economic and technological barriers. {userName} felt deep satisfaction, understanding that genuine social justice work establishes cascading effects of positive change that extend infinitely beyond specific interventions, transforming individual lives and establishing pathways to success that benefit entire communities for decades to come."
        ]
      },
      {
        type: 'silly',
        text: "The celebration got wonderfully chaotic when the new high-speed internet was so fast that it seemed to make everything in the community center move at super-speed too! Students were typing so quickly their fingers became blurs, the {favoriteAnimal} mascot they'd adopted for the center started doing victory laps around the computers, and even the {favoriteFood} in the snack area seemed to be bouncing with excitement! \"Technology celebration overload!\" {userName} laughed as confetti somehow started shooting out of the printers and everyone began doing the \"Digital Equality Dance\" that had absolutely no choreography but maximum enthusiasm!",
        microVariants: [
          "The victory party reached hilariously absurd proportions when the newly installed ultra-high-speed internet connectivity appeared to accelerate everything within the community center to comically supernatural velocities! Student typing speeds achieved blur-level intensity, their adopted {favoriteAnimal} technology mascot initiated celebratory sprint circuits around the computer workstations, and the {favoriteFood} refreshments seemed to vibrate with technological excitement energy! \"Extreme digital celebration syndrome!\" {userName} giggled uncontrollably as the printing equipment spontaneously generated festive paper explosions while everyone simultaneously invented the \"Internet Equality Boogie\" featuring zero planned choreography but unlimited joyful enthusiasm and community spirit!",
          "Their success celebration escalated to magnificent levels of technological silliness when the revolutionary high-speed internet installation seemed to energize every element within the community center with supernatural acceleration properties! Students achieved typing velocities that defied human capability, their beloved {favoriteAnimal} center mascot performed enthusiastic victory circuits around the computing infrastructure, and even the {favoriteFood} snack supplies appeared to pulsate with digital celebration energy! \"Maximum connectivity celebration chaos!\" {userName} burst into laughter as office equipment began producing spontaneous confetti displays while the entire community simultaneously created the \"Digital Justice Dance Party\" featuring absolutely no organized movement patterns but unlimited collective happiness and triumphant community celebration energy!"
        ]
      },
      {
        type: 'triumphant',
        text: "At the National Youth Social Justice Awards ceremony, {userName} stood before hundreds of advocates and policy makers as they received the highest honor for educational equity activism. \"Young leaders like {userName} demonstrate that age is no barrier to creating systemic change!\" declared the keynote speaker. \"Their comprehensive approach to addressing digital inequality has not only transformed their local community but has become a national model for bridging the digital divide. They have proven that when we combine research, community organizing, and unwavering determination, we can dismantle barriers and create opportunities for all students to reach their full potential!\"",
        microVariants: [
          "During the prestigious National Conference on Educational Justice and Social Change, {userName} accepted the supreme recognition for youth leadership in equity advocacy while addressing an audience of hundreds of social justice professionals and governmental policy architects. \"Extraordinary young advocates like {userName} prove that transformational leadership transcends all age limitations and demographic boundaries!\" proclaimed the distinguished keynote presenter. \"Their systematic methodology for confronting technological inequality has achieved remarkable success in revolutionizing their immediate community while simultaneously establishing a nationally recognized framework for eliminating digital access disparities. They have conclusively demonstrated that through the strategic integration of empirical research, grassroots community mobilization, and persistent commitment to justice, young people can systematically dismantle institutional barriers and establish comprehensive opportunities for all students to achieve their maximum academic and personal development potential!\"",
          "At the International Summit on Youth Activism and Social Transformation, {userName} received the highest possible distinction for educational advocacy excellence while presenting to an assembly of global social justice leaders and international policy development experts. \"Remarkable young change-makers like {userName} establish definitively that meaningful systemic transformation recognizes no age restrictions or experiential limitations!\" announced the internationally renowned keynote address presenter. \"Their comprehensive strategy for addressing digital educational inequality has generated extraordinary impact within their local community while creating an internationally studied model for systematic elimination of technological access barriers. They have provided irrefutable evidence that when young activists combine rigorous investigative research with strategic community organization and uncompromising dedication to social justice principles, they possess the capability to systematically eliminate institutional inequities and construct inclusive educational environments where every student can fully realize their unlimited academic, creative, and professional potential!\""
        ]
      },
      {
        type: 'reflective',
        text: "Standing quietly in the evening light filtering through the community center windows, watching students of all ages working together on their dreams and assignments, {userName} felt a profound understanding settle in their heart about their role as a social justice advocate. \"Real change happens when we see inequity and refuse to accept it as inevitable,\" they reflected with mature wisdom. \"Every person deserves equal access to the tools they need to succeed, and it's our responsibility to work together to tear down the barriers that prevent that access. The work is never finished, but every step forward creates possibilities that didn't exist before.\"",
        microVariants: [
          "Within the peaceful twilight atmosphere permeating the community learning center, observing students from diverse backgrounds collaboratively pursuing their educational aspirations and creative projects, {userName} experienced profound philosophical clarity regarding their identity as an advocate for social equity and justice. \"Authentic transformation occurs when we witness systematic inequality and categorically reject its acceptance as an unchangeable reality,\" they contemplated with developed intellectual maturity. \"Every individual merits equivalent access to the educational resources and technological tools necessary for personal success and professional development, and it becomes our collective moral obligation to collaborate systematically in dismantling institutional barriers that prevent equitable access to these fundamental opportunities. Social justice work represents a continuous process rather than a destination, but each progressive achievement establishes new possibilities for human development that previously remained beyond reach or imagination.\"",
          "Surrounded by the tranquil evening ambiance within the renovated community educational facility, witnessing learners representing various demographic backgrounds engaging cooperatively in pursuit of their academic objectives and personal interests, {userName} achieved deep philosophical comprehension concerning their role as an advocate for systematic social change and educational equity. \"Meaningful social transformation emerges when we observe institutional inequity and absolutely refuse to acknowledge its existence as a permanent or acceptable condition,\" they reflected with sophisticated intellectual understanding and emotional maturity. \"Each person deserves equivalent opportunity to access the educational infrastructure and technological resources essential for achieving their full potential and realizing their aspirations, and it becomes our shared ethical responsibility to work collectively toward systematic elimination of structural obstacles that prevent universal access to these basic human rights. The pursuit of social justice represents an ongoing commitment rather than a completed objective, but every incremental advancement creates expanded opportunities for individual and community development that were previously impossible to achieve or even conceptualize.\""
        ]
      }
    ],
    reuse: {
      swappableElements: {
        "digital divide": ["educational inequality", "resource disparity", "technology gap", "access barriers", "opportunity gaps"],
        "community center": ["local library", "school district", "neighborhood association", "civic center", "youth organization"],
        "internet access": ["computer availability", "software licensing", "device ownership", "technical support", "digital literacy"]
      },
      weatherVariants: ["challenging", "complex", "demanding", "sophisticated", "intricate"],
      settingVariants: ["in their community", "throughout their city", "across their region", "within their district", "among their neighbors"],
      randomSeed: Math.floor(Math.random() * 10000)
    }
  }

  // Templates 2-5 would follow with similar complexity, depth, and sophisticated themes
  // Each targeting different advanced topics suitable for ages 11-13
];

export function getLevel4FallbackTemplate(templateIndex?: number): StoryTemplate {
  if (templateIndex !== undefined && templateIndex >= 0 && templateIndex < LEVEL_4_FALLBACK_TEMPLATES.length) {
    return LEVEL_4_FALLBACK_TEMPLATES[templateIndex];
  }
  
  const randomIndex = Math.floor(Math.random() * LEVEL_4_FALLBACK_TEMPLATES.length);
  return LEVEL_4_FALLBACK_TEMPLATES[randomIndex];
}

export function getLevel4FallbackTemplateCount(): number {
  return LEVEL_4_FALLBACK_TEMPLATES.length;
}