/*
 * ============================================================================
 * BUSINESS MODEL DOCUMENTATION - GUEST EXPERIENCE
 * ============================================================================
 * 
 * GUEST USER FLOW & BUSINESS RULES:
 * 
 * 1. 20-MINUTE TIMER SYSTEM:
 *    - Timer starts on page load when reading begins
 *    - Can pause, reduce time, or end session from floating timer
 *    - Timer ALWAYS enabled for guest users (cannot be disabled)
 *    - Session ends when timer reaches zero
 * 
 * 2. STORY ACCESS LIMITATIONS:
 *    - Netflix-style generation: 10+ pages generated by OpenAI
 *    - BUSINESS RULE: Can only read 6 pages per story (artificial cutoff)
 *    - Page 6 shows "Next Story" button (never see story endings)
 *    - This drives premium upgrade conversions
 * 
 * 3. CACHE & SESSION MANAGEMENT:
 *    - "Next Story": Clears cache, starts fresh 6-page cycle
 *    - Backward navigation: Same images preserved during session
 *    - Session end: All caches cleared comprehensively
 *    - Avatar-aware caching to prevent cross-session contamination
 * 
 * 4. AUTO-RESUME BEHAVIOR:
 *    - Can resume if timer hasn't expired and session active
 *    - Fallback avatar handling for corrupted avatar data
 *    - URL parameters for session management (?clearSession=1, ?resume=1)
 * 
 * 5. UPGRADE PATHS:
 *    - "Upgrade" and "Create Account" buttons lead to login/pricing
 *    - Premium users get unlimited time + live generation
 * 
 * 6. NEVER-ENDING STORIES:
 *    - Stories designed to continue forever theoretically
 *    - Guest limit at 6 pages is business rule, not story constraint
 * 
 * ============================================================================
 */

import { useState, useEffect } from "react";
import { DebugLogger } from '@/services/DebugLogger';
import { WelcomeHero } from "@/components/WelcomeHero";
import { MultiStepUserForm } from "@/components/forms/MultiStepUserForm";
import { FreeReadingSession } from "@/components/FreeReadingSession";
import { PremiumUpgrade } from "@/components/PremiumUpgrade";

import { LoginScreen } from "@/components/LoginScreen";
import { useSecurityMonitoring } from "@/hooks/useSecurityMonitoring";
import type { UserInfo } from "@/types";
import { guestSession } from "@/utils/guestSession";
import { StorySessionCache } from "@/services/storySessionCache";
import { SessionCacheManager } from "@/services/SessionCacheManager";
import { APP_CONFIG } from "@/config/appConfig";

type GuestState = "welcome" | "form" | "reading" | "upgrade" | "login";

export const GuestExperience = () => {
  const [currentState, setCurrentState] = useState<GuestState>("welcome");
  const [userInfo, setUserInfo] = useState<UserInfo | null>(null);
  
  // Initialize security monitoring for guests
  useSecurityMonitoring();

// Check for query parameters on component mount and attempt auto-resume
useEffect(() => {
  const urlParams = new URLSearchParams(window.location.search);
  const action = urlParams.get('action');

  // Safety: allow clearing any cached sessions via URL
  if (urlParams.get('clearSession') === '1') {
    try { guestSession.clearAll(); } catch {}
    try { StorySessionCache.clearCachedSession('guest'); } catch {}
    // Clean URL
    window.history.replaceState({}, '', '/');
  }
  
  if (action === 'new-story') {
    // User came from session ended page wanting to start new story
    setCurrentState("form");
    // Clean up the URL
    window.history.replaceState({}, '', '/');
    // Clear any previous guest session
    try { guestSession.clearAll(); } catch {}
    try { StorySessionCache.clearCachedSession('guest'); } catch {}
    return;
  }

  // Auto-resume guest session if enabled in config
  const allowOverride = APP_CONFIG.features.resumeOnRefresh.allowUrlOverride;
  const viaUrl = allowOverride && urlParams.get('resume') === '1';
  const enableResume = APP_CONFIG.features.resumeOnRefresh.guest || viaUrl;

  if (!enableResume) return;

  // Auto-resume guest session if active and timer not expired
  try {
    const active = guestSession.isActive();
    const endTs = guestSession.getTimerEndTs();
    const info = guestSession.getUserInfo();
    const now = Date.now();
    console.log('[GUEST RESUME] check', {
      active,
      endTs,
      hasInfo: !!info,
      now,
      remainingMs: endTs ? endTs - now : null,
      enableResume,
    });
    if (active) {
      if (endTs && endTs > now) {
        if (info) {
          console.log('[GUEST RESUME] resuming reading state');
          setUserInfo(info);
          setCurrentState("reading");
          try { localStorage.setItem('readingTimerEnabled','1'); } catch {}
          try { window.dispatchEvent(new CustomEvent('readingTimerToggle', { detail: true })); } catch {}
          return;
        }
        console.log('[GUEST RESUME] missing user info -> not resuming');
      } else {
        console.log('[GUEST RESUME] timer missing/expired -> clearing');
      }
      // Expired or invalid -> clear
      guestSession.clearAll();
      StorySessionCache.clearCachedSession('guest');
    }
  } catch (err) {
    console.warn('[GUEST RESUME] error', err);
  }
}, []);

  // Ensure reading timer is always enabled for guest sessions
  useEffect(() => {
    if (currentState === "reading") {
      try { localStorage.setItem('readingTimerEnabled','1'); } catch {}
      try { window.dispatchEvent(new CustomEvent('readingTimerToggle', { detail: true })); } catch {}
    }
  }, [currentState]);

  const handleGetStarted = () => {
    setCurrentState("form");
  };

const handleFormSubmit = (info: UserInfo) => {
  DebugLogger.log('auth', 'Form submitted with userInfo:', {
    name: info.name,
    avatar: info.avatar,
    avatarType: info.avatar?.type,
    avatarSkinTone: info.avatar?.skinTone,
    difficultyLevel: info.difficultyLevel
  });

  DebugLogger.log('auth', 'Avatar validation check:', {
    hasAvatar: !!info.avatar,
    hasAvatarType: !!info.avatar?.type,
    avatarTypeValue: info.avatar?.type,
    willTriggerFallback: !info.avatar || !info.avatar.type
  });

  // Add avatar validation and fallback handling (Fix #4)
  if (!info.avatar || !info.avatar.type) {
    DebugLogger.warn('auth', 'Avatar data missing or corrupted, applying fallback');
    DebugLogger.warn('auth', 'BEFORE fallback - avatar:', info.avatar);
    info.avatar = { type: "prefer-not-to-answer", skinTone: "medium" };
    DebugLogger.log('auth', 'AFTER fallback - avatar:', info.avatar);
  } else {
    DebugLogger.log('auth', 'Avatar validation passed - no fallback needed');
  }

  DebugLogger.log('auth', 'Final userInfo being set:', {
    name: info.name,
    avatar: info.avatar,
    avatarType: info.avatar?.type,
    avatarSkinTone: info.avatar?.skinTone
  });

  setUserInfo(info);
  try { guestSession.setActive(true); guestSession.saveUserInfo(info); } catch {}
  // Clear all caches with new unified cache manager to ensure clean separation
  const avatarType = info.avatar?.type === 'prefer-not-to-answer' ? 'neutral' : info.avatar?.type;
  DebugLogger.log('story', '[GUEST DEBUG] About to clear cache with SessionCacheManager.clearOnNextStory:', { 
    userId: 'guest', 
    avatarType,
    infoAvatar: info.avatar 
  });
  try { 
    SessionCacheManager.clearOnNextStory('guest', avatarType); 
    DebugLogger.log('story', '[GUEST DEBUG] SessionCacheManager.clearOnNextStory completed successfully');
  } catch (error) {
    DebugLogger.error('story', 'SessionCacheManager.clearOnNextStory failed', error);
  }
  setCurrentState("reading");
};

const handleBackToWelcome = () => {
  setCurrentState("welcome");
  setUserInfo(null);
  try { guestSession.clearAll(); } catch {}
  try { StorySessionCache.clearCachedSession('guest'); } catch {}
};

  const handleUpgrade = () => {
    setCurrentState("login");
  };

  const handleCreateAccount = () => {
    setCurrentState("login");
  };

  const handleSubscribe = (planId: string) => {
    // Redirect to pricing page for subscription
    window.location.href = '/pricing';
  };

  const handleBackToReading = () => {
    setCurrentState("reading");
  };

  switch (currentState) {
    case "welcome":
      return (
        <div className="animate-fade-in">
          <WelcomeHero onGetStarted={handleGetStarted} onSignIn={handleCreateAccount} />
        </div>
      );
    
    case "form":
      return (
        <div className="animate-fade-in">
          <MultiStepUserForm 
            onSubmit={handleFormSubmit} 
            onBack={handleBackToWelcome}
            isPremium={false}
          />
        </div>
      );
    
    case "reading":
      return userInfo ? (
        <div className="animate-fade-in">
          <FreeReadingSession 
            userInfo={userInfo}
            onUpgrade={handleUpgrade}
            onCreateAccount={handleCreateAccount}
            onHome={() => setCurrentState("welcome")}
            onNewStory={() => setCurrentState("form")}
            isPremium={false}
onSessionEnded={async (stats) => {
  // Clear ALL session caches comprehensively
  try {
    const { SessionCacheManager } = await import('@/services/SessionCacheManager');
    SessionCacheManager.clearOnSessionEnd('guest', userInfo?.avatar?.type);
  } catch (error) {
    DebugLogger.warn('performance', 'Failed to clear session caches, using fallback', error);
    // Fallback clearing
    try { guestSession.clearAll(); } catch {}
    try { StorySessionCache.clearCachedSession('guest'); } catch {}
  }
  window.location.href = `/session-ended?stats=${encodeURIComponent(JSON.stringify({...stats, isPremium: false}))}`
}}
          />
        </div>
      ) : null;
    
    case "upgrade":
      return (
        <div className="animate-fade-in">
          <PremiumUpgrade
            onBack={handleBackToReading}
            onSubscribe={handleSubscribe}
          />
        </div>
      );
    
    case "login":
      return (
        <div className="animate-fade-in">
          <LoginScreen 
            userInfo={userInfo} 
            onBack={userInfo ? handleBackToReading : handleBackToWelcome} 
          />
        </div>
      );
    
    default:
      return (
        <div className="animate-fade-in">
          <WelcomeHero onGetStarted={handleGetStarted} />
        </div>
      );
  }
};